### ISSUE TITLE
Copystriking review videos?

### ISSUE THREAD

**Issue by JMAAGames** [Realm667/WolfenDoom#1022]
Hey, just a quickie of a heads up, did you guys copyright strike my review video of Blade of Agony?

If so, why?

And if you did, you know that's pretty f'ed up, right?

I hope Daniel Gimmer knows about this, he's deeply getting into some legal trouble if he seriously goes around copystriking videos CRITICIZING his work, which BTW, is based on an IP HE DOESN'T OWN but that actually Bethesda owns.

**Comment by Tormentor667** [comment]
As already commented on another platform:

> The video was reported because it used copyrighted material, the copyright strike is legit. You have no ownership for photos and portraits of authors from the Blade of Agony team. Using it interfers with the DMCA and we will continue to protect our authors personal rights and therefore hunt down any kind infringement as well as attacks or verbal offensiveness against us. Keep that out of your review and chances are high that your 120 GB of BoA footage won't go to waste yet another time.

**Comment by JMAAGames** [comment]
You know you're full of shit, right?

Just because I harshly criticized your game, doesn't mean you should weaponize the legal system against the review video. It will get you into serious legal trouble as you're copystriking videos for a game based on an IP that you don't own.

There's a thing called "fair use" and it exists for a good reason, it is to avoid copyright crybabies like you taking down videos because you were too butthurt to take actual criticism.

**Comment by Tormentor667** [comment]
Just because my or other authors’ faces are on the Blade of Agony page doesn’t mean that is free to use for everyone out there and this has nothing to do with „fair use“. 

„Fair“ would have been to post a video review on YouTube without insulting the Blade of Agony authors (and don’t deny that, comparing me with Hitler is an insult). Now you are simply tasting your own soup.

Change your video review or expect it to be deleted in the future as long as you don’t care about copyright or proper and adult behavior.

**Comment by JMAAGames** [comment]
IT'S JUST ONLY YOUR GODDAMN FACE, YOU DOLT.

**Comment by Tormentor667** [comment]
Goodbye.
