### ISSUE TITLE
Door closes too fast

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1049]
I think it has something to do w/ the fixes from #1019 , as now in c2m3 the church door closes very fast (<1 sec.) instead of being open for a few seconds. This makes shooting quite hard...

![Screenshot_Doom_20210917_223358](https://user-images.githubusercontent.com/77861029/133851984-877e6ee5-893f-47c3-bc54-d7fe8144425d.jpg)

**Comment by x3003** [comment]
>now it stays open indefinitely

It doesn't have to stay open indefinitely, so why not close it after about 8 secs, like it used to be ?

**Comment by Ozymandias81** [comment]
Because the plan for that commit was to improve the door behavior, and have a big old rusty church door which opens only from a side, and one door only, it is better to let it stuck in place like on C1M1 Hotel doors or C1M2 upstairs broken door and have a proper way to hide and aim/shoot behind the unmovable door. Also it would be a bit weird to see such a big door open/close. Consistency and gameplay reasons.

**Comment by x3003** [comment]
>Also it would be a bit weird to see such a big door open/close.

Well, pretty much all doors in the game close all the time, which is also weird. But he, that's the game.   ¯\_(ツ)_/¯
