### ISSUE TITLE
[C2M2] - Invisible wall and issue with Ryan

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1075]
With the git version, in c2m2, at this spot ryan can't follow you because of an invisible wall. You can't even push him through.
I think this happens after you get the green key, but can't be sure.
He does follow you when you get to the low path.

![Screenshot_Doom_20211120_000031](https://user-images.githubusercontent.com/77861029/142702292-30e891a9-57bf-47e6-8b1e-6cdfc64bda93.png)

![Screenshot_Doom_20211120_000108](https://user-images.githubusercontent.com/77861029/142702323-59c317c0-5454-4134-8e33-d213aa48ee8d.png)

**Comment by hawkwind3** [comment]
I just now also tested with the latest git version and did not have this issue. As a test to save time, I copied ryan and placed him at sector 2919. Ryan and BJ had no trouble walking past lines 11336 and 11693. I used a releatively recent gzdoom dated 26/10/21.

**Comment by x3003** [comment]
You can try my savefile.
gzdoom is 4.8 pre 77

[save12.zip](https://github.com/Realm667/WolfenDoom/files/7574305/save12.zip)

**Comment by hawkwind3** [comment]
Unfortunately, that savegame file does not show up in-game, even though I placed it in the Save folder, and I used gzdoom 4.8 pre77. Others will need to test this.

**Comment by x3003** [comment]
>Unfortunately, that savegame file did not show up in-game for me, even though I placed it in the Save folder,

Maybe unzip it first ?

**Comment by hawkwind3** [comment]
That is exactly what I did. Save file is save12.zds. It did not work for me. Interestingly, in that .zdz, you have 3 saved games ...

**Comment by Tormentor667** [comment]
Can you both test the map from the beginning to the end without cheating and let me know if the problem still persists?

**Comment by x3003** [comment]
I already did play from the beginning, no cheats, almost the hardest level.

**Comment by hawkwind3** [comment]
save file now runs. But I get this crash when trying to load it .
![c2m2error](https://user-images.githubusercontent.com/35204218/143723362-e132a2a6-85aa-4fa6-a6e8-b8e7a789477a.jpg)
..

**Comment by x3003** [comment]
yes, that's with gzdoom v4.6 and boa 3.1.

**Comment by hawkwind3** [comment]
I was using gzdoom 4.8 pre77 and boa 3.11

**Comment by x3003** [comment]
>I was using gzdoom 4.8 pre77 and boa 3.11

Try the git version in a seperate directory and see if it works.

**Comment by AFADoomer** [comment]
This happens because Ryan is set to respect monster-blocking lines when you enter that room.  There are block monster lines around the conveyor belt so that Ryan won't accidentally run into the green poison.  The line that Ryan is stopped on in the pictures, as well as the mirroring line on the other side of the stairs, are also set to block monsters, though I can't see why.

**Comment by hawkwind3** [comment]
@AFADoomer ...

You stated ...

This happens because Ryan is set to respect monster-blocking lines when you enter that room. 

So is there special scripting going on here ? If that is so, I would like to be pointed to in the code where this is the case. I'm guessing that x3003 would to. Normally, monster blocking lines would not block Ryan and allies.

**Comment by AFADoomer** [comment]
Yes.  This handling is in place to keep Ryan from following you into the acid conveyor.  Just setting him to non-moving (ACS script 20) isn't enough, because if he somehow ended up standing on the conveyor, he'd fall into the acid.

When the player crosses line 10458 to enter the room, the RyanBlock ACS script is run, which un-sets the NOBLOCKMONST flag on thing 86 (Ryan).

When the player crosses line 10460 while leaving the room, the RyanBlock ACS script is run with a parameter of 1, which re-sets the NOBLOCKMONST flag on thing 86 (Ryan).

The screenshots show Ryan at a position that corresponds to the location of line 11336.  This line, as well as lines 11423 and 11383 are flagged to block monsters - incorrectly, I think.

Because he has been set to be blocked by monster blocking lines, those lines are now blocking him.  Your tests probably didn't show this problem because you didn't walk through the door and over the lines to get into the room.

This should now be fixed as of f0df21543de0316b0081b414d4bcba0a8022f76b.

**Comment by hawkwind3** [comment]
Ah! I see now. I can at last confirm x3003's bug report. My testing confirms bug is fixed. Now, just for x3003 to confirm as well, since it is his report.

**Comment by Tormentor667** [comment]
@hawkwind3 @x3003 just for the record: Thanks so much for your time and effort testing Blade of Agony on and on. You are great, you really are! These reports help so much!

**Comment by x3003** [comment]
Thx.

Seems fixed, so can be closed ?!

**Comment by hawkwind3** [comment]
@x3003 

Feel free to close it.  :)
