### ISSUE TITLE
Douglas still doesn't react.

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1079]
This suppost to be fixed, but w/ a quite recent git version in c2m4, douglas still doesn't react when the enemy is all around him. Except when enemies coming out of the house on the left side.

![Screenshot_Doom_20211121_152838](https://user-images.githubusercontent.com/77861029/144323426-ead979a3-edd9-41ac-97a9-b6492b9eab65.png)

**Comment by Tormentor667** [comment]
If I recall correctly, there is no proper fix towards this at all. What do you think @Ozymandias81 ?

**Comment by x3003** [comment]
Well, he **does** fire at the enemies coming from the house on the left side, so why not when they're in front of them ?!

**Comment by Ozymandias81** [comment]
Because the actor is standing there "still" and doesn't use LOOKALLAROUND flag, or maybe not properly @x3003 . There could have been 2 ideal "fixes" for this part of the map imho:

1 - Let Douglas "spawn" inside the truck at drive place, we could use a "cut" sprite for him so to handle the thing without using weird flat sit frames (thought we could see him "severed" sitting onto the chair)
2 - Let's find a way to "activate" him only when enemies are present inside tagged sectors, but let's keep him around the truck
3 - Verify if the LOOKALLAROUND flag and the actor setup is "set" properly on map

Gonna check it now @Tormentor667
