### ISSUE TITLE
[Coop] Crosshair is not available for players 2-4

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1110]
Very strange behaviour on the HUD crosshair.  I think the problem is, that the other players entering get the Cutscene tokens but only the player who skips the cutscene got it removed again.

*Confirmed*
It's the problem that CutsceneEnabled doesn't get removed from all other players.

**Comment by AFADoomer** [comment]
The CUTSCENE_START and CUTSCENE_STOP scripts in (most?) maps that have a cutscene use GiveInventory and TakeInventory to add/remove the CutsceneEnabled item, so only affect the first player.  

Replacing all of these calls with GiveActorInventory and TakeActorInventory, both with a TID of zero (so that the item is added/removed from all players, per the wiki), should fix this.

So:
`GiveInventory("CutsceneEnabled", 1);` becomes `GiveActorInventory(0, "CutsceneEnabled", 1);`
and
`TakeInventory("CutsceneEnabled", 1);`  becomes `TakeActorInventory(0, "CutsceneEnabled", 1);`

**Comment by Tormentor667** [comment]
Sorted in 352d38816a0e7ec66f44a3ce80f34bbc08cb1b9f
