### ISSUE TITLE
bars are gone

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1118]
With the latest git version, the bars left and right are gone. How to get them back ?

![Screenshot_Doom_20220102_025401](https://user-images.githubusercontent.com/77861029/147864076-cb7a1c6c-cec1-4de6-97d0-81bd086dd622.png)

**Comment by AFADoomer** [comment]
Get in a situation where you need them and they will appear.

Or set the boa_hudmeterfade cvar to '1.0'.

**Comment by x3003** [comment]
Yeah, but fading the staminameter in and out is annoying.

**Comment by Tormentor667** [comment]
Maybe we could add an option that says if the bars are permanently displayed or not.

**Comment by AFADoomer** [comment]
Yeah, that's why it's configurable via a CVAR - I just didn't add a MENUDEF entry for it.  

You can set the transparency value that the bars will fade out to (0.0 being fade to invisible and 1.0 not fading at all), with the default currently being 0.0, and 1.0 restoring the old drawing behavior and not fading.

**Comment by AFADoomer** [comment]
Added a menu entry in a209ac4822337196fcc58f038eda7e6670bb7ed2.

Options > Display Options > HUD Options > HUD meter translucency when full

**Comment by Tormentor667** [comment]
Very good, everyone pleased, issue closed :)
