### ISSUE TITLE
[coop] questionmark stays after pickup

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1125]
With the latest git version, In 1 player coop mode. when picking up the paper, the questionmark remains. But for another player there's nothing to pick up.

![Screenshot_BoA_20220113_220026](https://user-images.githubusercontent.com/77861029/149409270-a531aba4-f7fe-40f3-992c-aa8fda54258c.png)

**Comment by Tormentor667** [comment]
The question mark is deactivated so it is fine, isn’t it?

**Comment by x3003** [comment]
Why not remove it then ?

**Comment by AFADoomer** [comment]
It would be trivial to make these fade out instead of going gray...  But why change it?

This is the same behavior as in single player; the icon gets grayed out when a player comes within range of it.  If it were removed and a player chose not to pick up the associated item for some reason, there would no longer be a marker to highlight it.
