### ISSUE TITLE
ink ribbon clue

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1176]
I think most ppl have no clue what this is or what this does or should do. Maybe someone can add a clue in the game !?

![Screenshot_Doom_20220203_135146](https://user-images.githubusercontent.com/77861029/153415372-6bbf7860-444d-45cf-ba3d-041b530e7894.png)

**Comment by Tormentor667** [comment]
It’s actually just an Easter egg without a function

**Comment by x3003** [comment]
hmm, an easter egg w/o an egg...

**Comment by AFADoomer** [comment]
Using typewriter ribbons at typewriters (both found in the level) is how older Resident Evil games let you save...

**Comment by x3003** [comment]
Ahhh, never played RE, so....

**Comment by Gaerzi** [comment]
You could make it obvious (for people who don't know about RE) that there's no point in looking for an ink ribbon by changing the text to something like "You have no ink ribbon in your inventory to save your progress... you'll have to just use the save menu instead!"

**Comment by AFADoomer** [comment]
It works fine as-is.  I do agree that the message could be tweaked to make it clearer that this is just an easter egg.  

Alternatively, we leave this message in place and actually add ink ribbon pickups strategically throughout the level.  We could alter the script so that if you *do* have ink ribbons in your inventory, they get removed and the player is rewarded with gold (or some other item) and a "What game did you think you were playing?  Have some gold instead." message, or something like that.

**Comment by Tormentor667** [comment]
Yes, this sounds like a good improvement of the actual easter egg - it adds another twist and makes it worth thinking about "Where can I get ink ribbons?"

**Comment by AFADoomer** [comment]
OK, added an ink ribbon item and handling for the typerwriter in d7a029c63a2c9bc016c23a9e7e309500a016e07b.
