### ISSUE TITLE
[CaptainJ] Uploaded because fun.

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1198]
![grafik](https://user-images.githubusercontent.com/10298439/154566478-bff7b38f-e08e-4e9c-a888-db53d20eaad6.png)

**Comment by MuadDib90** [comment]
_...long minutes before..._

A: Stop aiming at me, Hans!
B: You drew first, Otto!
A: Because you were doing that... that thing... with your hand!
B: I was scratching my butt, for Hitler's sake! Herr "Freund".
A: As far as I am concerned, "you" could be the spy!
B: Sounds exactly what "a spy" would say!
A: Don't make me laugh, Hans. You know I am not kiddin'. Put-that-down.
B: Yeah, I always knew you have no sense of humour, but this is absolute bottom.
A: I am warning yo-
B: Whaaat?! Otto! You're not suppose to say that. Don't tell me you didn't rehearse last night!
A: Nun... You know. Meine Frau came along aaand...
B: Schweigen! Someone's behind the window!
...


The thing that comes to my mind the instant I saw the image 😄

**Comment by x3003** [comment]
Y sometimes something funny happens. Here the shot was sooo hard, the enemy went straight through the wall.

![Screenshot_Doom_20220219_151529](https://user-images.githubusercontent.com/77861029/154805212-caf66e7c-f40f-4ff0-acc1-aca956774d66.png)
