### ISSUE TITLE
[Delta Touch] Attempting to use the Kar98k scope insta-crashes the game.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#1204]
As of commit 8d6c48c, attempting to use the Kar98K's scope in any way will insta-crash the game. Will there be a CVAR or some other option to revert to the shaderless zoom on a per-player basis?

GZDoom version: v4.7.1
Delta Touch version: v4.6 (user and post shaders disabled)

**Comment by AFADoomer** [comment]
Oh, God damn it.  Fucking Delta Touch.

**Comment by AFADoomer** [comment]
Reverted the commit.

**Comment by Tormentor667** [comment]
Any chance of letting delta touch update to make this feature work?

**Comment by AFADoomer** [comment]
There's literally nothing here that didn't work in GZDoom over a year ago.  I have no idea why it doesn't work.

**Comment by Shockwave508** [comment]
@Tormentor667 Delta Touch v4.6 is the latest version.

Delta has always been known to be generally-incompatible with shaders designed for desktops. I do recall that a workaround fix for the projector screen in INTERMAP was implemented. Perhaps something similar can be arranged for the Kar98K scope, as a CVAR, so everyone can still play the game.

**Comment by Tormentor667** [comment]
That would be cool if we find a workaround - afaik, @Talon1024 took care of that. Generally, I'd like to avoid removing improvements to keep compatibility with Delta Touch for all sakes. Is there a chance that DT catches up with the features instead?

**Comment by Talon1024** [comment]
That workaround was a1556dd5a5b3b4798784fcc35b8123d6d8641ebf, and it involved opening the shader in [GLSLViewer](https://github.com/patriciogonzalezvivo/glslviewer) and taking a bunch of screenshots.

It may not be possible to make the advanced Kar98k scope work properly in the GLES renderer or Delta Touch, because it's not a simple animation like the old video shader. IIRC the new Kar98k scope effect uses camera textures and makes the scope look stretched near the edges of the circle, and that's impossible to emulate using an animated texture.

**Comment by AFADoomer** [comment]
It doesn't even do that (though I had planned to add something similar).  All the shader was doing was making the camera texture fullbright so that the image isn't affected by brightness of the player sector.  

This particular implementation uses a model to overlay the scope image and the camera image and allow both to be smoothly scaled/zoomed easily.  Delta Touch probably doesn't like the camera texture being used as a model skin.

**Comment by Talon1024** [comment]
> All the shader was doing was making the camera texture fullbright so that the image isn't affected by brightness of the player sector.

In that case, a `BRIGHT` label on the scoped Kar98k states or a brightmap should be sufficient.

**Comment by AFADoomer** [comment]
Brightmaps don't seem to properly apply to a camera texture - at least not when they are used as a model skin.  And BRIGHT makes the entirety of the scope overlay bright, not just the camera image.

I'll try to rework this to use a shape canvas instead of the model, I guess...

**Comment by Tormentor667** [comment]
Is this issue still relevant?

**Comment by DungeonMaster555** [comment]
Тестовая версия Delta touch 4.7  с самой стабильной версией gzdoom 4.8.2 
https://drive.google.com/file/d/1Rl6PvHgTwmkSVoUo8F1O-nCSTDUUBeOs/view?usp=sharing

**Comment by DoomJedi** [comment]
Test version of Delta touch 4.7 with the most stable version of gzdoom 4.8.2 (google translate)
Much faster than to demand english  and wait for a day or 2 - takes half a minute.

**Comment by Tormentor667** [comment]
I think it's not my job to translate people who are not interested in giving the effort to write in a more common international language than russion. I mean, schreibe ich deutsch die ganze Zeit?
