### ISSUE TITLE
Message Log shortcut

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#1216]
@Talon1024 
Could you program the shortcut for Message Log so the player can also leave the message log, not just enter it; similary to Objective shortcut?

**Comment by MuadDib90** [comment]
> Do you mean with a toggable key?

Yes.

**Comment by MuadDib90** [comment]
Unfortuntelly, it doesn't work. :( 
b6c05a3

**Comment by MuadDib90** [comment]
Hmm, CAPS LOCK.
You think it could be this?

**Comment by Talon1024** [comment]
Unfortunately, yes. When the menu is in "GUI Capture" mode, GZDoom only records a subset of the keys available on the keyboard, which means the Caps Lock key becomes an "unknown" key. I've added a workaround in 08d99593437edf138d40b2f3a7c5c1fc84a0816f.

**Comment by MuadDib90** [comment]
Bad news, doesn't work for me...

**Comment by AFADoomer** [comment]
The only way that I know of to capture Caps Lock is to disable GUI capture (`menuactive = WaitKey;`) and use an OnInputEvent override.  

There's no defined constant for Caps Lock in the EDoomInputKeys enum, but it returns a DirectInput keyscan code of 0x3A when pressed (DIK_CAPITAL).

I'd say this would be fine, and you could just query those inputs against bound keys, but that's difficult with non-US keyboard mappings...  (i.e., AZERTY keyboards swap Q and A - same problem as with those users needing to type IDDAD instead of IDDQD for god mode in Doom.)
