### ISSUE TITLE
animation looks wrong

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1267]
In c3m6_a, the animation of this actor looks odd. He first shoots at you, looks left. Then centers, shoots, and looks right and so on.

![Screenshot_Doom_20220816_223214](https://user-images.githubusercontent.com/77861029/193396793-0d916bd2-9f90-48fa-aef5-4ba580db491f.png)

**Comment by Tormentor667** [comment]
Has some behaviour code been changed lately @Talon1024 ?

**Comment by Ozymandias81** [comment]
Since the actor is flagged with the stand fucntion, it checks for the player in "phases" and also the visibility might be obstructed by the z-height (for what I remember). This behavior might change from GZDoom build. It requires then to be tested with GZDoom 4.10, which is the one we are gonna use forever now (no more devbuilds).

**Comment by Username-N00b-is-not-available** [comment]
This actor used the incorrect state sequence, ```See.Statisch``` instead of ```See.Sniper```... Fix upcoming.
