### ISSUE TITLE
Random dude here asking a question.

### ISSUE THREAD

**Issue by LiterallyMadeThisAccountForOneQuestion** [Realm667/WolfenDoom#1280]
On all my light projections, such as spotlights, search lights, briefing room projector, lamps, even explosions or smoke I get these little pixelated bands or circles around them and I have no idea how to make them go away. Is there an option causing this? Please help. I legit made this account just to ask this. Any and all help much appreciated. It's just weird to have onion rings flying in the sky or in rooms.
![Weird onion rings](https://user-images.githubusercontent.com/120346976/206940887-4845b09e-1b10-4b1b-9d60-451002c85fbe.png)

**Comment by Talon1024** [comment]
That happens because:
1. GZDoom does not support [clamping](https://learnopengl.com/img/getting-started/texture_wrapping.png) individual textures, unless a shader is used to force the effect, and that isn't the case currently.
2. The model uses [this texture](https://github.com/Realm667/WolfenDoom/blob/master/models/lightbeam.png), which tiles seamlessly horizontally, but not vertically.
