### ISSUE TITLE
Shield give too low health

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1284]
In c2m0_b, when picking it up, this shield only gives 40% health, which isn't much. It used to be 100, but why so low now ?

![Screenshot_Doom_20221231_151547](https://user-images.githubusercontent.com/77861029/211144576-67d7288f-a4f2-4acd-86bc-beb9e129f145.png)

**Comment by Tormentor667** [comment]
That's definitely a bug. Does it only happen in this map?

**Comment by x3003** [comment]
You only get **this** shield in this map. Think you can buy it later on, but then @ 100%

**Comment by Tormentor667** [comment]
So buying it gives 100% but collecting it gives 40%?

**Comment by x3003** [comment]
Yep. Checked an old vid from pagb666 and there the shield is at 100%

**Comment by Talon1024** [comment]
I think the shield is at 40% because the laser beam is cutting part of it off. The shield should be at 100%, based on [the code](https://github.com/Realm667/WolfenDoom/blob/master/scripts/actors/items/powerups.zs#L1777), but those lasers do a lot of damage, so perhaps the laser in the screenshot should be removed?

**Comment by Tormentor667** [comment]
It's not on permanent anyway, isn't it?

**Comment by x3003** [comment]
The laser couldn't have damaged it. It's on the block i'm pointing at, which is outside the lasers range.

**Comment by Username-N00b-is-not-available** [comment]
Can not reproduce this. A possible explanation is that @x3003 was hit by a cloud of homing missiles from already dead Roboters.
