### ISSUE TITLE
no 100% score

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1311]
In c2m6_b, you can never get a 100% kill score, cause you can't kill the last enemy. He can't be killed for a good reason, so maybe the killcount should have 199 instead of 200 here ?!

![Screenshot_Doom_20230430_092810](https://github.com/Realm667/WolfenDoom/assets/77861029/17ae566c-306b-42a3-b934-c90f48d875e3)

**Comment by x3003** [comment]
Would be nice.

**Comment by x3003** [comment]
The fix doesn't work. You can now kill the last enemy, w/o being registered as killed. So you still can't get a 100% score.

![Screenshot_Doom_20230729_155713](https://github.com/Realm667/WolfenDoom/assets/77861029/9ef833dc-3cc9-44d1-801c-2a440887db51)

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Very strange! A few days ago I've got 100% kills on this map, on the lowest skill (+I used a knife on this officer anyway).
Could you please remember whether there was an alarm raised during your playthrough? I mean the yellow alarm switches, not just exclamation marks above soldiers. I think it might be because of the soldiers that are spawned by these switches. Maybe the guards are spawned in walls somehow?

**Comment by x3003** [comment]
Dunno about the alarms, but the kill count was 194 before I killed this last one.
Rechecked. There seems to be 6 live enemies, 5 when I kill this officer. Which is strange as I really don't know where these enemies are and the counter should then be higher than 195.

![w1](https://github.com/Realm667/WolfenDoom/assets/77861029/4aa18584-947f-4a97-ae8b-e0c1a82a4989)
