### ISSUE TITLE
stutter framerate issue

### ISSUE THREAD

**Issue by mataski** [Realm667/WolfenDoom#1315]
No matter what setting, the potato lowest or most highest preset, post-processing all off, or literally everything off, when you move the mouse at any direction there's these small stutters and spikes and game does not feel smooth at all, it feels like game is capped at 30 fps or something.

But if you enable RTSS and e.g. cap it at 60 FPS, it's smooth straight line with no frame drops
![image](https://github.com/Realm667/WolfenDoom/assets/62036912/9534d8e6-6087-4666-ab41-98bd92a5e4ca)

Uncapped it goes up to 100+ on all lowest potato settings, but the issue still persists and does not improve at all.

I'm in first zone tutorial/training.

I never get this problem with any other GZDoom games.

Ryzen 2600x and GTX 1060, but it doesn't matter because issue still persists on all low with 100+ fps. Doesn't get capped on all max either, so I don't think it's a rig problem because RTSS would at least report dropping frames.

**Comment by Ozymandias81** [comment]
Which version of the mod are you playing, 3.0, 3.1 or the actual state of the repository here on github? GZDoom needs a good CPU core speed at least 3ghz or higher for better performance, Vulkan also helps but the CPU speed is the most important things. I developed BoA with AMD Vishera 6core 3.5ghz cpu. You also have telemetrics active with Nvidia Experience most probably, those turn down framerate anywhere (I experienced it with Skyrim and Descent Rebirth port, on my GTX 1060 6gb Turbo - With Experience on I lost 30fps on Skyrim and Rebirth was stuck to 60fps, without Experience I gained 30fps and more on Skyrim (70-80fps) and Descent was stuck at 200.

**Comment by Ozymandias81** [comment]
The problem might rely to the version of GZDoom shipped with 3.1 release, which was 4.6.0
With recent builds of GZDoom, said 4.10, your configuration will be saved on your User folder, so at least you will be able to try a "fresh" installment of the mod. We can only assume your issues, GZDoom is freeware software. Use Vulkan render, get rid of any resize filters and then also you might try to download the version present in this repository (not releases, but cloning the repository itself) since it has been improved further to future 3.2 release. The fact that you don't experience these problems with other GZDoom mods isn't exatly significative, BoA is known to be pretty advanced even compared with Total Chaos or unoptimized versions of Project Brutality or Brutal Doom. I can't say per the 144hz thing too, I don't have experience with modern monitors, just make sure that you have selected Uncapped framerate from GZDoom, or set it to 200.

**Comment by mataski** [comment]
So I don't know what I did, but I did go through millions of options and settings and now issue seem to be resolved.

Last changes I did were:
- Renderer: Vulkan, Hardware
- All options that has keyword 'resize' set to Off (use Option search feature)
- Run as admin, Full Screen Optimization off, DPI scaling override by Application
- Nvidia settings for boa.exe all default except VSYNC On, but Off in-game (G-SYNC monitor)

Also has something to do if you have multiple monitors with different refresh rate, e.g. 60hz vs 144hz and if you have something open on your 60Hz lets say YouTube/Twitch, etc. then for some reason game on 144hz scales down to 60Hz and so on. But I think that's Windows 10 issue in general.

¯\_(ツ)_/¯

**Comment by Ozymandias81** [comment]
Multiple monitors are usually a known problem while fiddling with GZDoom settings, as well chosing proper render method. Vulkan is way better in general and since 4.8.0 it got nice improvements. This is sadly not something we can always take care, it is something users must keep in mind with free software developed by passionate people. Hey at least no dlc and no minitransactions 👅

**Comment by Username-N00b-is-not-available** [comment]
We use a lot of copyrighted assets however :neckbeard:
