### ISSUE TITLE
C2M2 Operation Feuerdrone door becomes stuck

### ISSUE THREAD

**Issue by Arijit746255** [Realm667/WolfenDoom#1348]
Blade of Agony ver 3.1
This issue seems occasional (restarted the map 3 times hit this issue 2 times), but the double door, right beside the single, green key door, in map C2M2 gets stuck and does not open from either side. 
<img width="655" alt="Screenshot 2" src="https://github.com/Realm667/WolfenDoom/assets/68688926/f60d75c8-5f88-4cca-a5ea-5785f96450dc">
<img width="755" alt="Screenshot 1" src="https://github.com/Realm667/WolfenDoom/assets/68688926/9602d197-e892-4648-9f1b-538e2ecf95dc">

Door getting stuck will make it impossible to complete this map as we will not be able to get the green key. Had to use "noclip" to complete this map.

**Comment by x3003** [comment]
Do you have any addons enabled ? Some dead guards might be not so dead when having behaviour addon, so they might block the door.

**Comment by Username-N00b-is-not-available** [comment]
@Arijit746255 Could you please provide the savegame, as well as the source port version number? You wrote BoA v3.1, am I correct that you are playing the release version from the Realm667 site?

**Comment by x3003** [comment]
I reported this issue here: https://github.com/Realm667/boa-addons/issues/6

**Comment by Username-N00b-is-not-available** [comment]
Thanks!

**Comment by Arijit746255** [comment]
I have this savegame if it is needed. Thanks.
[save13.zip](https://github.com/Realm667/WolfenDoom/files/12494094/save13.zip)

**Comment by Username-N00b-is-not-available** [comment]
@Arijit746255 I forgot to post here that the problem was fixed (the half-dead guards just weren't calling A_NoBlocking), here is the newly compiled version in case you don't want to re-download the whole 370MB addon repository and build the archive yourself:
[behaviour.zip](https://github.com/Realm667/WolfenDoom/files/12560799/behaviour.zip)
It is to be renamed .zip->.pk3 since GitHub won't allow posting files of 'unknown' formats.
