### ISSUE TITLE
Objects (trees) pop up in the distance even though "max performance" is activated

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1372]
Today I noticed that objects slowly pop in, even though I set the performance settings to max. This is an example in C1M0 at the very start. At the beginning, this is my view:
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/41a56dea-8388-4e34-9686-2afc7936167b)

I need to walk down the canyon and return back to make all the trees visible.
![grafik](https://github.com/Realm667/WolfenDoom/assets/10298439/016079b1-f5a3-4a58-b547-dd4eacc8bd9b)

There is definitely something wrong with the object culling - maybe @AFADoomer or @Talon1024 have an idea?

In v3.1 this is working perfectly fine by the way, so it must be an issue with the current development version.

**Comment by hawkwind3** [comment]
Yep! I reported this issue August last year #1347. I came across a workaround but not ideal.

**Comment by Tormentor667** [comment]
I really hope one of the programmers can take a look. This is a critical issue

**Comment by hawkwind3** [comment]
I found that the simplest fix for me was to change line 44 in cvarinfo.txt from true to false.
As it is currently with boa 3.1 and gzdoom 4.6 setting to either true or false seems to make no difference.
Disclaimer ... works well in Windows, not sure about other gzdoom operating systems.

**Comment by Tormentor667** [comment]
I tried the fix mentioned here https://github.com/Realm667/WolfenDoom/issues/1347 but it doesn't work. A clean install doesn't work either.

> I found that the simplest fix for me was to change line 44 in cvarinfo.txt from true to false. 

The setting the cvarinfo.txt line 44 to "false"

`server bool boa_culling = true; // Enables/disables actor culling ** // Needs menu entry, possibly launcher choice`

I have no idea what it actually does (boa_culling), so I'd like to know from @AFADoomer @Ozymandias81 @Talon1024 what are the consequences when setting it to false or for what this has been implemented.

**Comment by AFADoomer** [comment]
This should be working properly again after 3d9d70302880e1eecdf769097843ce582f941b12.

The 'boa_culling' CVar turns on and off actor and effect culling.  Culling is selective deletion or re-adding of actors and effects to the map in order to reduce think time - so, for example, in C1M2 rain isn't constantly spawning in a portion of the map that you are nowhere near, and in this map hundreds of trees and other decorations that you can't see don't take up actor think time.

For me, this gives a significant performance boost.  

If you turn culling off, the engine runs the map vanilla style - all actors are always present and 'thinking' in the background.

**Comment by Tormentor667** [comment]
I had something like this in my memory but tanks for clearing up things - and for the proper fix.
