### ISSUE TITLE
[C1M2] No rain at the start

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#1395]
There is no rain at the start of C1M2 (Exodus). I took a quick look at the map in UDB, but the rain spawners are there at the start of C1M2, so I think the absence of rain has something to do with the culling system.

**Comment by AFADoomer** [comment]
I saw this last night but didn't get a chance to look into it...  The rain is there and spawning, but doesn't reach the ground. 

The culling code doesn't directly touch the new particles, so I'm not sure what's going on.

**Comment by AFADoomer** [comment]
OK, so this *is* the culling code - I thought the raindrops had been converted to particles.  

The problem is that the raindrops are being culled before they hit the ground.  The old code adjusted the z-height of the spawned drop based on the z-position of the highest player in the map.  I can re-add this to the rain at risk of losing some optimization.

**Comment by AFADoomer** [comment]
Updated in 9d458214de2b0827b59a1d3b5d250f4972cdfc8f
