### ISSUE TITLE
Path blocked

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1431]
In c3m5_b, there's something blocking the path to the left side of the crosshair.

![Screenshot_Doom_20240624_221753](https://github.com/Realm667/WolfenDoom/assets/77861029/3abf4052-d7dd-47df-87a0-e587c4f69e30)

**Comment by hawkwind3** [comment]
Could not reproduce. That said, I have just uploaded a new version of this map. My previous version caused a glitch at sector 3227. The upload has of this writing not been verified yet.

**Comment by hawkwind3** [comment]
Update ...

I can reproduce.

I bet you kicked open the door directly below and you kicked the door from inside the room. I only worked this out because I have come across the same issue in c2m1.

The only solution I can think of is to make those 4 doors below "non-kickable". Any better solution ?

Your thoughts @x3003 or anyone else.

**Comment by hawkwind3** [comment]
Fixed. Basically, just a matter of changing the heights of the 4 control sectors for the 4 doors below. C2M1 will be more of a challenge, as it has 2 3d floors above the swinging door ...

**Comment by x3003** [comment]
Seems fixed.
