### ISSUE TITLE
Douglas killed

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1440]
Something weird.
In c2m5_b, when Douglas walks away you can actually kill him.

![Screenshot_Doom_20240707_212650](https://github.com/user-attachments/assets/e430d59a-ec20-40df-b464-3b5fb4eb52a0)

**Comment by hawkwind3** [comment]
Definitely a bug. I could put a block everything at the door. but not the best fix. At the very start of that level, you dont get the red crosshair indicating not to shoot Douglas. You do at the start of c2m5_a. This bug is even in boa3.1.
For the moment I hope the programmers can fix this one properly. Good catch !

**Comment by hawkwind3** [comment]
Closed. But will open a separate issue regarding the missing red X "don't shoot me " crosshairs.
