### ISSUE TITLE
boa_c2_s.zip malware

### ISSUE THREAD

**Issue by laxdragon** [Realm667/WolfenDoom#158]
Windows detects that the file boa_c2.exe is infected with Trojan:Win32/Tiggre!rfn

This was from a fresh download from the moddb website.

**Comment by Ozymandias81** [comment]
There is no "fresh" download from ModDB page since it is still the C2 release,
Maybe you are not aware and didn't read my replies on the Mod page, but those are just Phalse Positives since the .exe file is an injected batch file with a custom icon and copyrights.
Check this comment to solve it: ["Phalse positives, please read my previous comments here... it is just an injected batch process that ".exe" file: it just executes gzdoom with boa_c2.pk3 file.
You can simply drag & drop the boa_c2.pk3 over the gzdoom.exe to run the mod."](http://www.moddb.com/mods/wolfendoom-blade-of-agony/downloads/blade-of-agony-chapter-2-v20-standalone/page/2#comments)

**Comment by Talon1024** [comment]
I'm writing something in the FAQ section of the BoA website right now.

**Comment by Ozymandias81** [comment]
@laxdragon 
It is label "invalid" merely because the .exe file is something that has been take care outside this repository, so doesn't belong here. Just that, thanks in any case. :+1:
