### ISSUE TITLE
Actors which needs to be fixed or improved

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#176]
After recently fixes done by AFA for the debris mound, we definitely need to see if actors can be improved or fixed once more, and possibly with this issue I'll keep track of problems noticed, so the list may be updated from time to time.

ALL THE FOLLOWING PROBLEMS NOTICED UNDER GZDoom g4.3pre-357-g1085287af 64bit

_**SOLVED**_
**ElectricalArc actors**:  their invisible puffs kills actors even where they shouldn't, and it happens for both variants (vertical/horizontal). As a test try on TEST_ACT map at the start, check your right side and walk along the walls until you are right down the ElectricalArc: you get killed, even enemies
![Screenshot_Doom_20191121_131248](https://user-images.githubusercontent.com/11136108/69337594-89b62c80-0c61-11ea-9ebc-ffd7c92b3969.png)

_**SOLVED**_
**PlayerFollower actors**: it seems that they can't climb or jump or in any case reach BJ if some actors or portals are in their way, noticed on C3M5_A when we kill all tanks and rendez-vous with Yevgeny. Sometimes when you are very far, the follower appears right behind you again and then all is good, but this would also prevent to have help from the follower in some situations. Also I didn't tested the prisoner on C1M2, but I heard from someone that it has similar problems on that map too behaviour-wise

_**SOLVED**_
**HeatEffectGiver inheritance with FireSpawner**: Torm said that HeatEffect doesn't get removed when a FireSpawner gets deactivated or activated, but I can't reproduce it

_**SOLVED**_
**Debris_Wood_FloorCeiling actors**: if they get hit from below, they doesn't "die", but just fall from where they are, like if gravity being set again (and also die since they are not shootable anymore). Jump inside the pool from TEST_ACT in front of you and aim to one of them
![Screenshot_Doom_20191121_132011](https://user-images.githubusercontent.com/11136108/69337721-d4d03f80-0c61-11ea-8d9e-510a3d0575bb.png)

_**SOLVED**_
**Enemies behaviour in general with Portals**: it seems that enemies aren't capable to see or target us if we stand in front of them "behind" an interactive portal. This is highly noticeable on C1M5 Hotel de la Mort restaurant and C3M5_A entrance to Chancellory

**Comment by Talon1024** [comment]
Regarding the FireSpawner, I was unable to reproduce the issue wherein the heat effect doesn't get removed when the actor is deactivated. I created a simple test map which allows the player to toggle a FireSpawner with a script, and I had no issues.

I used Thing_Activate and Thing_Deactivate to toggle the fire effects. I did not remove the FireSpawner from the map.

**Comment by Ozymandias81** [comment]
You are right, I simply reported what Torm said but neither I can't reproduce it. Gonna adjust that.

**Comment by Tormentor667** [comment]
Check the train area of C3M5_A. In one of the last train cabins before the crash and explosion happens, there is an inactive fire spawner. It adds the heat effect to the player screen despite being inactive.

**Comment by AFADoomer** [comment]
- Electrical arc issues should be fixed in fe940ce80176e34544c7ccdf1153240016f98a08.
- Playerfollower issues should be resolved as of db339d037f6cc6cd49dfd97e23dfe8dac957c402.
- FireSpawner activation problem should be fixed in 35edd0ad14ff4f1e7306fe94fb91c59f1a545bc0.
- Debris_Wood_FloorCeiling (and breakable vent and manhole cover) should be fixed in e332b74f549f17413c52eac5b3495ff51a0be9d0.
- The enemy behavior you're seeing with portals is normal for GZDoom with the portals configured as they were...  If you want enemies to be able to see though a line portal, the line portal must be set to "Static (Eternity style)".  Fixed for C3M5_A Chancellory entrance and C1M5 restaurant and salon entrances in 5971ff0c8003d8600c53cd3e205062a7947645bd.

**Comment by Ozymandias81** [comment]
About what Torm said, yes noticed that a while before you did the fix (which in the end was not possible to understand on my end due to zscript XD)
Aaaand yes, all your fixes have been set as _**SOLVED**_ , later will come with more in case I can't fix them (if I spot some). Atm busy with BlooM so expect some slow progress in November from me about BoA commitment, mainly to the fact that we are going to have another release near Christmas (brightmaps and actors rework from me)

**Comment by Tormentor667** [comment]
Awesome work guys :)

**Comment by Ozymandias81** [comment]
Okay guys here we go with some new stuff that's crucial and needs to be fixed, mainly from N00b tests at issue #178 

ALL THE FOLLOWING PROBLEMS NOTICED UNDER gzdoom-x64-g4.4pre-65-g78bae1f16

- [ ] Toilet soldier cause a crash when he wakes up from the toilet
![Screenshot_Doom_20200219_134439](https://user-images.githubusercontent.com/11136108/74835749-4f226580-531e-11ea-9dd3-fa8a3368fe38.png)

- [ ] Being killed by Goebbels produce another crash, now into Playerfollower
https://user-images.githubusercontent.com/59409713/74602804-c60cf380-50bd-11ea-945d-72b5cb973c05.png

- [ ] MengeleBomb kills anyone, even invulnerable players or playerfollowers, and can also kill Mengele itself... Could be related to GrenadeBase since the decorate code doesn't have any issues

**Comment by Ozymandias81** [comment]
That's true, really losing track of some stuff here and there... And well MengeleBomb has not been added by me originally, will find a way to fix later then, thanks again for you fixes!

**Comment by Ozymandias81** [comment]
I have managed to get one of the problems that N00b experienced with dying enemies: if you check the first 3 images from [here](https://imgur.com/a/TXmPWg3) you'll see that Scientist2 is dead but still behave as a living entity, he can't be killed though. It happened only once but on that particular zone I also got 2 crashes though, this with gzdoom-x64-g4.4pre-80-g9e5444f8a. Something related to the dodge feature maybe @AFADoomer ?

**Comment by Ozymandias81** [comment]
- [ ] @AFADoomer Sorry to bother you again, but spot something odd: on C3M6_B go to this place and walk all over the courtyard, everything seems fine. But once we look down the well, I get 2 fps and that stays forever. If I freeze, fps turns again better, but once I unfreeze slowdown happens again. If I remove the rope and its target, I don't get any slowdown, maybe something not set correctly on map for those actors or is the target too far from the rope? Or is it something different?

![Screenshot_Doom_20200308_181948](https://user-images.githubusercontent.com/11136108/76168183-804bc400-616d-11ea-9328-b032689fd525.png)

**Comment by AFADoomer** [comment]
It's because there are a crap-ton of bats in the well that are all trying to interact with the rope all at once.  Remove the bats via 'remove batfamiliar' of 'kill all' or whatever, and there's no lag.  

If we want to keep the effect of all of the bats flying out of the well, we need to get rid of the rope and figure out some other way to keep the player from falling down the hole...

**Comment by Ozymandias81** [comment]
Well forgot to say that I did my tests with and without bats, and without bats slowdown occurs once you try to interact with the rope with Use key, while going down. I am aware of the remove thing and at first glance thought it was that (where also the ropespawner explains that any actor which has ISMONSTER flag set, its interactivity is negate, unlike playerfollowers).

On a total different note, could it be possible for playerfollowers to cure players once we have less than 25hp? That could improve gameplay and turn battles less stressfull (obviously this shouldn't happen when morphing into tanks, but implement this only if you think that shouldn't haul thinkers). And about the slowdown I get on c1m4, it seems related to whizzer checks, since I noticed that thinkers jumps from 5-6 to 70-80 for each shot which crosses near me and enemies

**Comment by AFADoomer** [comment]
I get no slowdown when the bats aren't there.  Climbing has never worked well inside of the well because there's barely enough room for the player to fit beside the rope, but I don't get lag.

The playerfollower (Ascher specifically) already cures the player once he's below 40 health.  Set the heal trigger threshold via the 'PlayerFollower.HealPlayer' property.

**Comment by Ozymandias81** [comment]
Sorry for the health thing, since I am not the one who maps wasn't aware of that variable XD , but well not then some maps may use it and for a good reason. Will test C1M4 asap and tell you how it goes now, thanks :)

**Comment by Ozymandias81** [comment]
Okay @AFADoomer the problem comes from @Tormentor667 changes to the map somehow, since with [this commit](https://github.com/Realm667/WolfenDoom/commit/cfc90e05cfc6a1df3205e6efd621d093ba7455e6) I don't have any issues with thinkers... Wonder what is it though, maybe the ladder with the portal?

**Comment by Tormentor667** [comment]
Regarding C3M6_B: It's okay for me to remove the bats from the well or the rope and block the player, it's not really needed.

Regarding C1M4: The commit you linked is your own commit, I am not sure if you really mean that?

**Comment by Ozymandias81** [comment]
What I mean is that before your recent changes to the map, there were no stuttering problems, even using actual code for enemies which is demonstrated on the video. If you check c1m4 history, the map I used is the last commit I did for it then after that you did edits to the map. Why I am saying this? Well it is simple: I don't know exactly how many changes have been done to the map but the last I was aware of the ones done on my last commit for such map. So I assume that you have probably included something on the map that involuntarily have compromised map performance.

About the rope thing: it is fixed now, I will edit the well but keep the secret which is cool and also important for the player, specially after fighting all those bats (they'll come from another zone directly inside the courtyard, and also add block monsters lines over the well just to be sure)

**Comment by Tormentor667** [comment]
I can only imagine that the portals are the problem

**Comment by Ozymandias81** [comment]
Yes, it is caused by the first portal with the ladder going down, I tried removing actors from both portals but didn't solve the issue... Later I'll figure out what to do. The other portal works fine (last flak zone)

**Comment by Ozymandias81** [comment]
[Fixed C1M4](https://github.com/Realm667/WolfenDoom/commit/3f46be657fd3a32cae2c9a0874babfe689c8d15a) but there is a zone where riflemen doesn't see nor aim at you (it was the same even before my changes, but actor where less reactive since they had Ambush Player flag, now not set)

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer, @Ozymandias81, @Talon1024:

The code which is concerned with throwing projectiles in the Doom engine behaves quite simplistically. It is non-Newtonian, which is even more noticeable in BoA: for example, if you move with a constant velocity, do not turn and then try to shoot, you can see the projectiles diverge from the 'center of the screen', i. e. the line of fire (see video: [weapons.zip](https://github.com/Realm667/WolfenDoom/files/4414614/weapons.zip)). In this case the player's reference frame should be inertial, but it isn't.

I propose to add the shooter's velocity to the projectile's after spawning, so that they behave more realistically. For monsters this will be quite useless as they always stand still while hurling missiles (at least in original Doom; and, apparently, most of the basic enemies in BoA also do so), but for the player the improvement will be noticeable: as all their projectile weapons all shoot in a straight line (or don't they?), this will be a significant change. Also, as a first-order approximation this will fix the problem with Tesla Cannon to some extent (shown in the video).

The manipulations to accomplish the goal are quite simple, you can just change every instance of
```
A_FireProjectile("SomeTypeOfBullet", ...);
```
in the weapon code to

```
let bullet = A_FireProjectile("SomeTypeOfBullet", ...);
if (bullet) bullet.A_ChangeVelocity(vel.x, vel.y, vel.z);
```
I can do this myself, I just want to know if the team is interested in such things.

P. S. By the way, seeing one of my previous proposals (with tanks) uncovered that <strike>it was a shitty idea, like any other one</strike> in most situations, the turret movement is inadequate (for example, if a tank stands in a long 'corridor' such as the second one in C1M0, and the player strafes much while running to it, the tank just shoots at the walls). The algorithm should probably be enhanced: since we already have InterceptTarget, it would make sense to 'move' it to the position (like a solid object, considering every obstacle on the way) instead of 'teleporting':
https://github.com/Realm667/WolfenDoom/blob/492e904730b7096374ee460a80ebfa045325318e/scripts/actors/enemies/tanks.txt#L594

**Comment by Tormentor667** [comment]
I am okay with this change if @AFADoomer approves this.

**Comment by AFADoomer** [comment]
For simplicity's sake, I updated the base class that all of the player's bullet projectiles inherit from to account for velocity instead...  Also made a few other tweaks for pseudo-realism.  

Adding velocity to the Tesla cannon lightning fixes nothing; trust me, I've tried it...  I re-added it because, why not...  I think it makes things worse.

I'm not sure what you want from the tanks...  Strafing sounds like a fantastic way to avoid having a  tank aim at you, so this sounds like intended behavior.   

For any changes to the intercept code, I'll have to defer to @Talon1024 .

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer: thank you for the addition! I noticed a slight problem, though: if a bullet (for example, from kar98k) hits some enemy, it changes its pitch considerably (managed to capture the moment). This is even more noticeable with rapid-fire weapons.

<details><summary>Screenshot</summary>

![temp](https://user-images.githubusercontent.com/59409713/78179117-5aae9380-7469-11ea-8372-b7a95ea97b77.png)

</details>

Regarding Tesla, maybe the model just needs to be spawned or warped more often (didn't see the code for it), anyway it definitely is not the main goal for now.

As for tanks, I mean this.

<details><summary>Screenshot + madskillz</summary>

![Screenshot_Doom_20200401_224816](https://user-images.githubusercontent.com/59409713/78180092-ef65c100-746a-11ea-9b52-0bea84081722.png)

![temp](https://user-images.githubusercontent.com/59409713/78181170-95fe9180-746c-11ea-88c6-c13602d15733.png)

</details>

Also, FastProjectile's velocity can be modified this easily? Then, maybe there is a <strike>hack</strike> proper way to remove action of +NOGRAVITY on it?

**Comment by AFADoomer** [comment]
Ah, OK.  I see what you mean.  I don't know that there is a good way to make that change...

Rather than remove NOGRAVITY from the projectiles, I already added a slight downward velocity over time that scales with the projectile's speed (so that I can control the speed of fall, so that faster projectiles fall more slowly).
