### ISSUE TITLE
Flatpak not running, it is crashing. Ubuntu 18.04

### ISSUE THREAD

**Issue by lahtis** [Realm667/WolfenDoom#193]
Im using flatpak install flathub com.realm667.WolfenDoom_Blade_of_Agony

Fatal Error. 1 errors while parsing DECORATE script. 

GZDoom <unknown version> -  - SDL version
Compiled on Feb 26 2019

M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /app/share/games/doom/gzdoom.pk3, 635 lumps
 adding /app/share/games/doom/zd_extra.pk3, 132 lumps
 adding /app/share/games/doom/freedoom2.wad, 3595 lumps
 adding /app/share/games/doom/boa_c2.pk3, 14294 lumps
I_Init: Setting up machine state.
CPU Vendor ID: AuthenticAMD
  Name: AMD Phenom(tm) II X4 965 Processor
  Family 16 (16), Model 4, Stepping 3
  Features: SSE2 SSE3 3DNow! 3DNow!+ HyperThreading
I_InitSound: Initializing OpenAL
  Opened device Built-in audio Analogue stereo
  EFX enabled
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 100: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 297: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 328: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 367: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 403: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/actors/enemies/base.txt, line 267: Default values for parameter of virtual override will be ignored!
6 warnings while compiling boa_c2.pk3:zscript.txt
Script warning, "boa_c2.pk3:actors/models.txt" line 2593:
Tried to define class 'SpotLight' more than once. Renaming class to 'SpotLight@boa_c2.pk3@actors/models.txt'
Script error, "boa_c2.pk3:scripts/actors/playerfollowers.txt" line 321:
Type mismatch in function argument
Gtk-Message: 19:09:51.929: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:09:51.930: Failed to load module "canberra-gtk-module"

**Comment by lahtis** [comment]
Otherwise snap package working. But not sounds.

**Comment by Username-N00b-is-not-available** [comment]
Hello, @lahtis! Thank you for your report.
I get the same errors as in your first report when I try to launch the Chapter 2 release commit on modern GZDoom, so that is most probably a broken compatibility issue (sooner or later this fate strikes every Doom modification).
On the other hand, sounds work fine when launching the modification with the GZDoom version 3.1.0 (which is bundled with it on the [Blade of Agony's website](https://boa.realm667.com/index.php/download)), at least on Windows. This may be a problem of some configuration property in GZDoom. I am no expert in this topic, especially for Linux, but you can try changing the MIDI Device and/or Sound Backend properties in Sound options, maybe it will work as a temporary solution.

**Comment by lahtis** [comment]
Thanks for information. But my sound is too easy fixed. Turn the power on the speaker. :D What sounds working.

**Comment by Username-N00b-is-not-available** [comment]
Thank you for mentioning BoA on the wiki! You can also write something about GZDoom on its Doom page, since it is available for Linux in various repositories and packages (and you can also build it from source on your machine), and there are countless modifications made for it. As for Realm667 ones, you can start with [Knee-Deep in ZDoom](https://www.realm667.com/index.php/en/projects-mainmenu-50/104-projects/finished/255-knee-deep-in-zdoom-kdizd), [The Ultimate Torment & Torture](https://www.realm667.com/index.php/en/projects-mainmenu-50/104-projects/finished/289-the-ultimate-torment-a-torture), [Stronghold: On the Edge of Chaos](https://www.realm667.com/index.php/en/projects-mainmenu-50/104-projects/finished/236-stronghold-on-the-edge-of-chaos) and a (very) recent remaster of [The City of the Damned](https://www.doomworld.com/forum/topic/113723-the-city-of-the-damned-remaster-v20-rc3/). For more WADs from the community you can check the list at [the Doom Wiki](https://doomwiki.org/wiki/List_of_notable_WADs), but it is, of course, not exhaustive; many gems hidden in the depths of the [/idgames](https://doomworld.com/idgames) archive await Doomers who want more levels to play.
Also, there was an astonishing recent mapset release by one of your compatriots: [Lost Civilization](https://www.doomworld.com/forum/topic/105215-lost-civilization-22-map-fun-and-nonlinear-megawad-now-with-download-link/), you can add that as well!

Given that the sound problem was resolved, :-) what is left is the compatibility with new GZDoom versions. To the team: I don't know if it would be better to update the packages now (can the flatpak author @Alexander-Wilms still be reached?) or just postpone it for a few weeks (_hopefully_ not months...) until the final Chapter 3 release?

**Comment by lahtis** [comment]
Yes, the intention would be to write about this. Thanks for these links. 
So I updated some new information to the pages (Doom, GZDoom...) 
But I’m interested in what Realm667 does, so they’ll be more soon.

**Comment by Ozymandias81** [comment]
Since I don't have Linux I can't take nor test any actions related to the issue, but indeed gzdoom version used here is too old

**Comment by ekMonkey** [comment]
This is occurs because flatpak version uses GZDoom 3.7.2. You can easelly check it in flatpak manifest file https://github.com/flathub/com.realm667.WolfenDoom_Blade_of_Agony/blob/master/com.realm667.WolfenDoom_Blade_of_Agony.yaml at 86 string. So, to fix this bug need to change  version of GZDoom to 3.1.0 at 86 string and its sha256 at 87 string.

**Comment by Ozymandias81** [comment]
Once I'll get a positive confirmation from @lahtis about the issue being fixed, since I don't own a Linux based OS and can't directly test it, I'll consider this closed (or lahtis can do it). @ekMonkey do you mean version 4.1.0 and not 3.1.0 right?

**Comment by Talon1024** [comment]
The WolfenDoom snap package [uses GZDoom 3.3.2](https://github.com/mcphail/boa/blob/master/snapcraft.yaml#L18).

Anyway, Chapter 3 should be out relatively soon, and I plan to notify @Alexander-Wilms and @mcphail as soon as Chapter 3 comes out.

**Comment by lahtis** [comment]
1 errors while parsing DECORATE scripts. Exit.

sudo flatpak install flathub com.realm667.WolfenDoom_Blade_of_Agony
Remote ‘flathub’ found in multiple installations:
1) system
2) user
Which do you want to use (0 to abort)? [0-2]: 1
Installing in system:
org.freedesktop.Platform.GL.nvidia-440-100/x86_64/1.4 flathub f0a2a5ecfc68
com.realm667.WolfenDoom_Blade_of_Agony/x86_64/stable  flathub e99b246bdad0
  permissions: ipc, pulseaudio, wayland, x11, devices
Is this ok [y/n]: y
Installing: org.freedesktop.Platform.GL.nvidia-440-100/x86_64/1.4 from flathub
[####################] Downloading files: 7/7 104,2 MB (14,9 MB/s)          
Now at f0a2a5ecfc68.
Installing: com.realm667.WolfenDoom_Blade_of_Agony/x86_64/stable from flathub
[####################] 31 metadata, 33 content objects fetched; 418559 KiB trans
Now at e99b246bdad0.


flatpak run com.realm667.WolfenDoom_Blade_of_Agony
GZDoom <unknown version> -  - SDL version
Compiled on Feb 26 2019

M_LoadDefaults: Load system defaults.
W_Init: Init WADfiles.
 adding /app/share/games/doom/gzdoom.pk3, 635 lumps
 adding /app/share/games/doom/zd_extra.pk3, 132 lumps
 adding /app/share/games/doom/freedoom2.wad, 3595 lumps
 adding /app/share/games/doom/boa_c2.pk3, 14294 lumps
I_Init: Setting up machine state.
CPU Vendor ID: AuthenticAMD
  Name: AMD Phenom(tm) II X4 965 Processor
  Family 16 (16), Model 4, Stepping 3
  Features: SSE2 SSE3 3DNow! 3DNow!+ HyperThreading
I_InitSound: Initializing OpenAL
  Opened device Sisäinen äänentoisto Analoginen stereo
  EFX enabled
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 100: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 297: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 328: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 367: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/menus/iconlistmenu.txt, line 403: Default values for parameter of virtual override will be ignored!
boa_c2.pk3:scripts/actors/enemies/base.txt, line 267: Default values for parameter of virtual override will be ignored!
6 warnings while compiling boa_c2.pk3:zscript.txt
Script warning, "boa_c2.pk3:actors/models.txt" line 2593:
Tried to define class 'SpotLight' more than once. Renaming class to 'SpotLight@boa_c2.pk3@actors/models.txt'
Script error, "boa_c2.pk3:scripts/actors/playerfollowers.txt" line 321:
Type mismatch in function argument
Gtk-Message: 00:12:35.491: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:12:35.491: Failed to load module "canberra-gtk-module"

**Comment by lahtis** [comment]
Snap package working ok in Ubuntu, but flatpack not.

su 5. heinäk. 2020 klo 19.23 Kevin Caccamo (notifications@github.com)
kirjoitti:

**Comment by Ozymandias81** [comment]
For that version (Chapter 2) you'll need max around 3.2.5 sadly, if I am not wrong @lahtis

**Comment by ekMonkey** [comment]
> 
> 
> Once I'll get a positive confirmation from @lahtis about the issue being fixed, since I don't own a Linux based OS and can't directly test it, I'll consider this closed (or lahtis can do it). @ekMonkey do you mean version 4.1.0 and not 3.1.0 right (which still could have issues with actual state of the repository)? And btw shouldn't this place [a better link](https://github.com/coelckers/gzdoom/releases) to track new releases of GZDoom?
> 
> EDIT: nvm about the 3.1.0, that's about the Chapter 2 release. In that case 3.2.1 is better for stability, if I recall correctly.

Hello, yes i mean chapter 2 release. Flatpak version is chapter 2 release and it needs suitable version of GZDoom (not the one that is used now).

**Comment by Tormentor667** [comment]
I wonder: Is this something we need to act or is this something, people from outside our team need to act?

**Comment by Tormentor667** [comment]
Closed for now (abandoned?)
