### ISSUE TITLE
Preparation for a Chapter 3 snap package for Linux

### ISSUE THREAD

**Issue by mcphail** [Realm667/WolfenDoom#194]
Hello everyone. The progress on Chapter 3 has been amazing. When you're ready to announce a release, I'd like to update my snap package to give Linux gamers the best possible experience. Thanks to having permission to distribute a snap for chapters 1&2, there are over 5 thousand active users of the snap package and feedback has been great.

There are a few moving parts I'd like to nail down:
- Can I have permission to create and distribute an updated snap when Chapter 3 is complete?
- What is the currently-recommended version of gzdoom?
- Are there any new recommended configuration tweaks?
- Any know caveats, such as SDL version problems etc?
- Is there a migration path for old save files, or should users be encouraged to start a fresh campaign?

I really appreciate the passion which goes into this project, and hopefully we can continue to collaborate on the snap release!

**Comment by Username-N00b-is-not-available** [comment]
Hello, @mcphail! Thank you for the kind words.

> What is the currently-recommended version of gzdoom?

Currently we are using the latest development build of GZDoom; its new features are used extensively, so the answer is probably the last stable build released before Chapter 3 completion. I recall that the minimum OpenGL version for GZDoom might have changed during these years, not sure on how will that impact the users. For old hardware, there is LZDoom maintained by drfrag, though.

> Is there a migration path for old save files, or should users be encouraged to start a fresh campaign?

The maps have been changed extensively throughout these years, and for most maps (I bet even all of them) the old savegames will not be applicable at all.

**Comment by mcphail** [comment]
Thanks! I can get started on doing some preparatory work.

**Comment by Ozymandias81** [comment]
Hey @mcphail long time! Feel so cool that there are so many users for your snap package, one day I'll try myself it when I'll decide to go for Linux. Let's get to the point, adding over what N00b said already:

- PERMISSION: For me it is okay, sure you'll need to wwait for the full mature release since it is planned to have also a separate executable for the mod, and probably as well something similar for Linux users

- GZDOOM VERSION: Atm it is always the latest build, mostly I bet that BoA will release with GZDoom 4.4/4,5 in mind as officialbuild to use

- TWEAKS: Oh well I have added countless ones, there is already a set of predefined settings which floats from Potato mode to Ultra mode, plus expect actors optimizations and maps tweaks as well.... Everything else anyway can be find under the usual Enh. Options menu

- SDL: GZDoom comes to be compatible with gpus that can run at least OpenGL 3.3+ or Vulkan support, and running the game under different ports such as LZDoom or QZDoom may have unexpected glitches, issues and bad things which we aren't responsible. We are already fighting with GZDoom development as usual, and personally idk what other problems could happen also under Linux. Indeed one thing that must not be done is to run external mods of any kind with BoA, as additional advice.

- SAVES: While as I previously said we have already issues with GZDoom development, recently AFADoomer fixed an issue with savegames being corrupted due to technical problems linked to actors "serialization", like some info about actors and such not being saved and causing abrupt crashes. We hope that the final version will have a mature build of GZDoom, unlike the 3.1.1 used for Chapter 2 which had several issues. And to reply your question, no saves won't be compatible at all since everything has changed so a fresh campaign will be the only choice.

**Comment by mcphail** [comment]
Much appreciated. That's perfect, and gives me everything I need to get planning the snap. I'm loving your work :)
