### ISSUE TITLE
Keyed Elevators in Operation: Paris are unclippable

### ISSUE THREAD

**Issue by m0rb** [Realm667/WolfenDoom#195]
Hey all.

All the color keyed elevator doors in Operation: Paris during my current playthrough require me to toggle noclip on/off in order to enter and exit.

Running gzdoom g4.4pre-300-g8c1db978b on Linux/x86_64, current WolfenDoom-master checkout.

**Comment by Username-N00b-is-not-available** [comment]
@m0rb: That's true, apparently I have added the blocking lines improperly when recently trying to fix the elevators. Just a small script error slipped in, fixed in https://github.com/Realm667/WolfenDoom/commit/3543d92243eaaafcc3e17ef0a7faf3bc281a4dfb. Thank you for the message!
Note that you may be lucky to retain your savegames.

**Comment by Tormentor667** [comment]
Well done!
