### ISSUE TITLE
Intermission videos to C2M6 B & C don't work: "AimingCamera 313: Can't find TID 0"

### ISSUE THREAD

**Issue by 2-4601** [Realm667/WolfenDoom#209]
Open console and try to change to c2m6_b and c2m6_c:
```
]map c2m6_b

----------------------------------------

C2M6_B - Operation: Hades

AimingCamera 313: Can't find TID 0

]map c2m6_c

----------------------------------------

C2M6_C - Operation: Hades

AimingCamera 313: Can't find TID 0
```
![Screenshot_Doom_20200718_165915_compressed](https://user-images.githubusercontent.com/174176/87854155-89695080-c918-11ea-9ddc-20166ee8d9fa.jpg)

This also happens when you play the game normally, i.e. exit c2m6_a and enter c2m6_b.

GZDoom version: g4.4.2-m
BOA version: 1e3523a

**Comment by AFADoomer** [comment]
These should probably just be changed to security cameras, since they just look straight ahead and have no aim point...

**Comment by Tormentor667** [comment]
I wonder where these issues come from. Nothing has been changed and we have a lot of problems lately with aiming cameras and the TID = 0 bugs.

**Comment by AFADoomer** [comment]
We're seeing this error now because of [this commit](https://github.com/coelckers/gzdoom/commit/0631670a66800c7af47ac06e434b363c101620c6) in GZDoom.  The warning was uncommented (rather arbitrarily) as part of troubleshooting an issue where cameras weren't properly following the target...  Though it was commented out in the original code 10 years ago.

**Comment by Ozymandias81** [comment]
I had in fact to fix [TITLEMAP cameras](https://github.com/Realm667/WolfenDoom/commit/77bafec7002b55d0e09ebf10ddad0ac61c6ecfd1) since the first time it got reimplemented.
