### ISSUE TITLE
Performance regression by commit "7ccac677e Effects optimizations"

### ISSUE THREAD

**Issue by 2-4601** [Realm667/WolfenDoom#210]
Game hangs to a total crawl when radio overlay shows up.

First try the previous commit to ensure that everything works fine:
1. `git checkout` 08aac73b0
1. `./build.sh --no-update`
1. `gzdoom -file ../wolf_boa-08aac73b0-20200718.pk3 +map c2m6_c`
1. Wait for Douglas' radio overlay to show up

**Result:** Nothing bad happens, everything works fine

---

Then test the "Effects optimizations" commit:
1. `git checkout` 7ccac677e
1. `./build.sh --no-update`
1. `gzdoom -file ../wolf_boa-7ccac677e-20200718.pk3 +map c2m6_c`
1. Wait for Douglas' radio overlay to show up

**Result:** FPS drops to 0, game becomes unresponsive to input, sound still plays normally in the background

---

- Linux 5.7.9
- i7-4700MQ 
- Intel HD Graphics 4600
- GZDoom g4.4.2-m - 2020-06-16 19:19:13 +0200 - SDL version (Compiled on Jun 17 2020)

**Comment by 2-4601** [comment]
If I delete my `gzdoom.ini` the issue goes away. Did 7ccac677ed549095efdae6de5e90e8b52413a10d introduce something that invalidated previous settings? I have adjusted my performance settings to get better FPS (I was using 3908012ee then).

**Comment by Ozymandias81** [comment]
While it is hard for us to understand exactly your config and setup (I am a win7 64bit user not Linux, that maybe Talon1024 could help), you are playing BoA with an internal gpu that's Intel, well known to be a problem with the sourceport. Beside that, you are also playing under an old build of gzdoom, said 4.4.2, while we develope our progres through daily builds, for example I am with 4.5r70. Surely your .ini file had some outdated setups, but I can't be sure if that happened because of optimizations or something else. For that we'll need AFADoomer response if he is aware of something that may have caused it (torches cvars for example)

**Comment by 2-4601** [comment]
I ran some tests on the same computer using Win10 64bit. Tested GZDooM 4.4.2 and 4.5r70 – both with the internal GPU and dedicated GPU (NVIDIA GeForce GT 730M). I was able to reproduce the same issue as laid out in my original post with all combinations using the old ini file. But when I removed the old configuration everyting worked again.

Thus the culprit seems to be some oudated setting which does not work anymore after 7ccac67.

I'm fine with closing this right away but if @AFADoomer wants to have a look at this I'll keep it open for now.

---

My original intention was to playtest episode 3 when I saw @Tormentor667 mentioning on some forum that it's almost ready. But some secret maps were not complete so I couldn't play it through. Then I decided to have a quick look at the old episodes, just to see if there was something new... but I failed to have just a quick look and found myself still playing several hours later :)
To justify my "wasted" time I decided to do atleast something "useful" and report the issues I encountered while playing :)

**Comment by AFADoomer** [comment]
I don't suppose that you kept a copy of your old .ini file for me to be able to compare to try and track down what changed?

**Comment by 2-4601** [comment]
Here's the full ini file:
[gzdoom-issue210.ini.txt](https://github.com/Realm667/WolfenDoom/files/4943907/gzdoom-issue210.ini.txt)
(Github forced .txt extension)

**Comment by AFADoomer** [comment]
No idea what happened...  I don't see anything in the .ini that's odd.

**Comment by Ozymandias81** [comment]
Just tested a couple of things regarding actors optimizations @AFADoomer .... Now C3M1_A intro feels better, I gain around 3-4 fps so instead of starting at 14/15 I get 18/20 and that's pretty nice! But I have noticed something regarding cone lights: everytime I cross the lod value I have set in my custom configs, another light and another cone gets spawned in place, turning actors very very bright. Related to multiple lods at the same time or issues with master? Also BJ uniform at the camp gets overriden by the palette, even if I convert sprites as PNG format without palette.
![Screenshot_Doom_20200722_182508](https://user-images.githubusercontent.com/11136108/88203592-5ab9e580-cc4a-11ea-923f-94d85b4ae5e6.png)

![Screenshot_Doom_20200722_180610](https://user-images.githubusercontent.com/11136108/88203577-55f53180-cc4a-11ea-9932-d7f13246ed9e.png)

**Comment by AFADoomer** [comment]
Hmm...  OK, I see what's going on there with the cone lights; it looks like there is literally one light class (WallLight1Lit) with different code from all of the others, where deactivating the wall light actor doesn't remove the cone, so when the light actor is spawned back in, the old cone is still in the map, and a second gets spawned on top of it.

I haven't done anything with the player sprites or palette...

**Comment by Ozymandias81** [comment]
Fact is for mappers taste and easy-to-go, some static actors aren't switchable, you just need to place on maps and stop.
Regarding BJ ikr you didn't anything related to it, it is something I have spot a couple of months ago and still didn't manage to fix.
Did a commit a while ago for prisoners btw :)

**Comment by AFADoomer** [comment]
The cone light issue should be fixed now - ModelBase-inheriting actors no longer automatically get culled, since I don't have a good way of dealing with any additional actors that were spawned by the original actor if there was no master/child relationship set up.  I'm sure there were other second- and third-order effects (multi-part models, probably), but I hadn't noticed them.

By the way - thanks for the concrete feedback on the optimizations.  I've done testing and benchmarking for myself, in places where I have had particular problems with performance in the past, but it's nice to see that the changes are working well for people on different hardware, too.

**Comment by Ozymandias81** [comment]
I will let you know more for each actor how they'll perform, surely I noticed thinkers went down specially for rain spawner.
My major issue is with smoke actors, I'll test them intensely and tell you how they have changed, best place to test them are near smoke ambient actors and also clouds on C3INTRO scene when Darren dies, before your updates I had like 4-6 fps.
To test bats bets place are c1m5 catacombs and c3m6 maps, tomorrow or later I'll start testing thinsg and for this reason rework completely TESTMAP, since have too many actors on the same map doesn't help really for playtesting.

**Comment by AFADoomer** [comment]
Thanks...  i haven't rewritten fire and smoke spawners yet, so there's more to gain there.  Fire spanners are in work (mostly done) now, just cleaning up some sloppiness.

**Comment by 2-4601** [comment]
Just tested f7854d968af410b6279942686e35c9a70c74e393 and I can report that the original issue seems to have been solved. (Though for some curious reason I don't get the radio overlay at all in the beginning of c2m6_c.)

**Comment by Tormentor667** [comment]
Has the radio overlay also been fixed or addressed?

**Comment by 2-4601** [comment]
Tested 0ad68dbb9a10f2605cc40e4c892d3fa2b1abd01d. Even if I start from scratch (i.e. delete all config files), the radio overlay does not show up on c2m6_c. The intro demo (map to Iceland) also does not show up anymore.

**Comment by Tormentor667** [comment]
The intro was uncommented, just activated that again and it runs just as usual before. Can you explain with radio overlay is meant?

**Comment by 2-4601** [comment]
> Can you explain with radio overlay is meant?

![Screenshot_Doom_20200728_230105_compressed](https://user-images.githubusercontent.com/174176/88715358-7a5b7d00-d126-11ea-9f16-61a4c3aad187.jpg)

**Comment by Tormentor667** [comment]
Should work now as well, was part of the intro script.
