### ISSUE TITLE
Grenade travel distance affected by autoaim

### ISSUE THREAD

**Issue by davidxn** [Realm667/WolfenDoom#232]
Not sure why this happens, as I checked the Decorate and FPF_NOAUTOAIM is definitely set for the grenade A_FireProjectile...

Demonstrated on the training course here (when Youtube processes it). I discovered this by accident, but on trying to reproduce it found that it was actually fairly tricky to get the right angle to demonstrate it - I think it's aiming at the tank a little to the right. When this happens, grenades don't travel as far as you would expect.
https://youtu.be/o_YDMHvrkn4

I found this regarding some problems with FPF_NOAUTOAIM, but it was marked as fixed more than a year ago. https://forum.zdoom.org/viewtopic.php?f=2&t=63428 I'm on gzdoom g4.4.2.

**Comment by AFADoomer** [comment]
OK, so I've traced this problem...  Right now, this will only happen in the training area, not in normal gameplay.  It boils down to the proper handling of the FTF_NOAUTOAIM flag being dependent on the player having a weapon equipped.

Probably can probably be solved by tweaking the inventory clear handler to keep NullWeapon in the player's inventory in the INTERMAP instead of clearing everything out...

What's happening, if anyone cares:
- The grenade inventory item uses A_FireProjectile with the FTF_NOAUTOAIM flag to spawn a grenade
- A_FireProjectile internally calls SpawnPlayerMissile, correctly passing the 'noautoaim' boolean as true, because FTF_NOAUTOAIM was set
- SpawnPlayerMissile calls P_SpawnPlayerMissile internally, which contains [this line of code](https://github.com/coelckers/gzdoom/blob/e47f016b23a3146c9bc810ff21c2a3434dc0a716/src/playsim/p_mobj.cpp#L6798):
`if (!(aimflags & ALF_NOWEAPONCHECK) && source->player && source->player->ReadyWeapon && ((source->player->ReadyWeapon->IntVar(NAME_WeaponFlags) & WIF_NOAUTOAIM) || noautoaim)) { ... } `
Once you parse through all of those parentheses: The 'noautoaim' variable is only ever considered if the source of the projectile is a player and the player has a currently equipped weapon.  This means that if no weapon is equipped, the logic fails and falls through to the next block, which makes it autoaim.

**Comment by Tormentor667** [comment]
Thanks for the explanation, so if I understood this correctly, as long as you have a weapon, even if it is just the “Nullweapon” dummy, the line will work. It only fails if you really don’t have a weapon at all.

**Comment by davidxn** [comment]
Amazing detective work 💯
