### ISSUE TITLE
General audio discussion

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#270]
Currently they have this creepy voice that sounds like a zombie. Remember: Templars are no undead or supernatural but normal humans guarding the Spear of Destiny. Beyond I'd suggest adding slightly visible face to them, just as in the example attached (maybe a different from that can be created by @DoomJedi and added by @Ozymandias81 ). Again: They are no undead or supernatural enemies but guards of the Spear.
![SSCTA1](https://user-images.githubusercontent.com/10298439/89280649-3518dd00-d649-11ea-9a2d-77c777fddedd.png)

**Comment by Ozymandias81** [comment]
I am not happy of this issue since cultists have always been creepy enemies, usually guarding old pyramids or ruins filled with creepy enemies. Plus their voices have been added a year ago by me from hittieties language, and all of you where happy with it. I don't plan to change these enemies, turning them human will also make them with less personality instead like something that's inbetween living and undead.

**Comment by Tormentor667** [comment]
The sounds are still the old ones for me, am I doing something right?

Regarding the "facelift" (literally) the point is simple: Currently they feel like creepy undead monsters - but they are not. Can you remember the cultists from "The Mummy" with Brandon Frazier? These are the enemies I have in mind. They are only humands guarding the weapon, defending it from the Nazis and other people, no supernatural forces.

@AFADoomer @Talon1024 @DoomJedi @Username-N00b-is-not-available what do you think?

**Comment by Talon1024** [comment]
In the Tomb Raider games I've played, some of the enemies were humans kept alive for thousands of years by supernatural powers. These were Stormguards in Tomb Raider, and the [Deathless](https://tombraider.fandom.com/wiki/Deathless_Ones) in Rise of the Tomb Raider.

**Comment by Tormentor667** [comment]
> In the Tomb Raider games I've played, some of the enemies were humans kept alive for thousands of years by supernatural powers. These were Stormguards in Tomb Raider, and the [Deathless](https://tombraider.fandom.com/wiki/Deathless_Ones) in Rise of the Tomb Raider.

That's a good approach but as it is now, the enemies are described as "Templars" and these have definitely a different background than a Deathless.

**Comment by Ozymandias81** [comment]
We've discussed about only differ their sounds a bit from zombies afaik, and while I was wrong regarding how much time I've introduced new see sounds, here you are the relative commit.

https://github.com/Realm667/WolfenDoom/commit/65895d1fa42bb88ed8cf848c7bf5cb44be475ea0#diff-ad1588d76517dd34c49c3f901bce7fcf

**Comment by Tormentor667** [comment]
I can only tell that it's not what I had envisioned for the Templars. They wear crosses, have a christian background and so does the Spear. Why do they have a demonic voice? 

I am open to convince me to go for a different approach if it fits to the story.

**Comment by Username-N00b-is-not-available** [comment]
>Why do they have a demonic voice?

The cultists may have practiced uttering evil noises to scare the invaders.

I'd leave the 'see' sounds (the pitch-shifted phrases from hittities... I hope I didn't make a typo) in, change the 'pain' & 'death' sounds to more human (but with a substantially lower pitch than the soldiers' and officers' ones), and also **add 'active' sounds**: curses, spells or battle cries. I think that something along the lines of Blood's 'nonsense words that highly resemble Latin' would fit very well, we can even use Blood's fake language itself (but probably not the sound files, they are too well-known).

**Comment by Tormentor667** [comment]
Yes that could indeed work better.

**Comment by Ozymandias81** [comment]
I think G-Mota mages may have sounds we need... Will ask.

**Comment by Tormentor667** [comment]
Curious to see - or actually listen - how they sound :)

**Comment by Ozymandias81** [comment]
Gonna check asap and see if I can pack a zip here

**Comment by Tormentor667** [comment]
Just listened to them, sound okay, but the language is simply not right. I know it's surprisingly difficult to find something fitting.

**Comment by Ozymandias81** [comment]
Probably neither possible :thinking:

**Comment by Tormentor667** [comment]
Yes I think so

**Comment by Ozymandias81** [comment]
Cool then later will add them 😁

**Comment by Ozymandias81** [comment]
I guess after adding those sounds and also nitpicking actor name, I can close this then.

**Comment by Tormentor667** [comment]
Well, the sound is a placeholder as it is now but it still feels not right to me so I'd like to keep it open. Same goes for the faces.

**Comment by Username-N00b-is-not-available** [comment]
We have to deal with the music and sounds some more, and I would like to hijack this issue for general audio discussion.

1. The cultists still have unfitting sounds. With help of google translate I got some translations of phrases to Latin. I am aware that they are most probably incorrect, and to combat that I messed them up even further :D (BTW my changes were quite conservative, after such a long period of living in isolation the cult's language would have deviated from Latin a lot more):

<details><summary>My attempt at broken Latin</summary>

```
I am protecting the Holy Lance. -> Autem Lanca Sancta protegas.
Go away, intruder! -> Abi, medius!
Intruder! -> Intrusor!
The Lance is in danger! -> Sacerdos Lancam in periculo!
Attention, brothers! -> Operam, fratres!
Show them our strength! -> Ostendere nostros vires!
Stay away from the Lance, marauder! -> Discedite a Sacerdos Lancam, latronem!
Go away or die here! -> Surge vade tu hic aut mori!
Get out of my sight! -> Ex facie mea!
You do not belong here! -> Non hic te pertinent!
Run away or taste lead! -> Fugit, aut sapor plumbo!
```

</details>

What has been broken is mostly grammar (I 'simplified' it a bit to make the phrases shorter) and some spelling.
@Ozymandias81 What do you think of it as a speaker of Italian, a direct descendant of Latin? Is this a poor attempt?

2. I have just added Ryan sounds for C3M0_B, but for some reason the replacement death sound is not working, maybe because after death all the attributes are reset. Also probably the sounds should be made louder, could anybody please help me with this too?

3. My favourite wargame, sounds from which I have recently ripped for Ryan, also has 130MB of very well-done music tracks; hell, I really like the entire sountrack. Would you (@Tormentor667 @Ozymandias81) like me to upload them so some of them could be used in BoA? Same goes for sound files: the game contains lots of SFX sounds (which we can use e. g. for tank cannons — judging by sounds, in BoA the tanks now fire self-propelling rockets, as there is only 'pssshhh' instead of also a 'boom' when the missile leaves the gun), and lots of sounds for the troops (not only Soviet ones, there are also American, British and German voice packs) + there is lots of mission commentary said in Russian, so we have the opportunity to cut and paste some phrases from them too. Are you interested in these resources?

**Comment by Tormentor667** [comment]
**Regarding 1**: I really like the phrases, these fit perfect and I'd be happy to see them ingame. I just wonder: Who records them?
**Regarding 2**: As far as I can tell, this has been fixed meanwhile.
**Regarding 3**: Feel free to share these, I am always open for good _music_ that can be used in Blade of Agony :) Can you send them to me somehow? (www.wetransfer.com might work). In general I am also open to any additional or improved sound if you want to add some to the game (like improving the tank sounds). For our Soviets, we definitelys need Soviet phrases and audios. Maybe the INTERMAP could also improve from addition audio and specific voices for each actor, to make them sound more unique. If you want to take care of these on your own, I'd be very happy.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 
1. My voice is not suitable for this purpose, as I am too young. What's I am thinking about is that we already have some of your voice samples in BoA (e. g. C2M2 messages), so if you take the responsibility to record these, after a slight processing we can end up with a very good set of sounds (you should keep in mind that the letters should be pronounced in Latin way, it differs from today's European languages a bit). If @Ozymandias81 volunteers instead it would also be nice, since Italian is closer to Latin than other European languages. As a last resort we can use text-to-speech tools, some of them allow specifying correct phonetics for words, but this option will require more editing work from us.

3. Sent the music link to your email; I'll think a bit more about the sounds.

**Comment by Tormentor667** [comment]
Give me a few days I will come up with something ;)

**Comment by Tormentor667** [comment]
One question though: Can I take the google translate pronounciation in latin for granted?

**Comment by Ozymandias81** [comment]
While your latin phrases seems write good @Username-N00b-is-not-available , sadly I can't help record voiceovers due to my quite deaf conditions. But I might give it a try, even if I have never been into Latin (I studied as an accountant).

**Comment by Tormentor667** [comment]
I will take care of the audio recordings in the upcoming days.
