### ISSUE TITLE
Light cones and fog gets more transparent when getting close to them

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#296]
@nashmuhandes - I know Blade of Agony isn't your top-priority project but I really like the addition you made to the TCotD2 Remaster where fog gets more transparent when being closer and gets less transparent when being farther away. Do you think you could implement that mechanic into BoA as well - including taking care of the volumetric light cones?

The current implementation is good (thanks to @Talon1024 and @Ozymandias81) but it is not working yet on Fog and Clouds. Also it's in question if it makes sense to add them to Steam as well. (including ZyklonSteam).

- [x] Make the shaders from @Talon1024 also work on Fog and Clouds

**Comment by nashmuhandes** [comment]
@Tormentor667 I don't have much free time right now but what I can do is, make a minimal example file that maybe @Ozymandias81 can take care of to merge into BoA. I will see what I can do soon.

If I take too long to get back to this, feel free to @ me again

**Comment by Tormentor667** [comment]
Thanks kindly for the offer, that would be totally awesome.

**Comment by Ozymandias81** [comment]
So this is what I have come so far mixing 2 lumps from TCOTD and applying Vollight defs and such: due to fact that effects are controlled by the EffectsManager, so that's why atm it spam several cones until we are near it and wait for 10-20 secs to see it fading slowly (also conelights have Add instead of Translucent Fog from TCOTD2. Tested under C3M1_A, uncomment vollight from decorate and include vollight on zscript obviously to test it.

[vollight.txt](https://github.com/Realm667/WolfenDoom/files/5361330/vollight.txt)

**Comment by Tormentor667** [comment]
I will keep this uncommented, that's stuff that I have no idea of :) Maybe @AFADoomer and @Talon1024 can help here.

**Comment by AFADoomer** [comment]
The DietActor variants are basically the same as the SimpleActor which is already present.

Which actor are you using to test this effect?  Unless I've missed a change, the light fixture actors that spawn cones (nor the cones themselves) are set up to be culled by the effects manager.

**Comment by nashmuhandes** [comment]
@AFADoomer I suggest just using your SimpleActor class then, it makes no sense to duplicate similar classes this way.

If you (or anyone else) cares to do it, it's basically just a shader that sets the pixel's alpha depending on the camera distance. There is no actor code involved to achieve this effect.

**Comment by AFADoomer** [comment]
I just pushed an actor-code based version...  The shader approach is probably better; will have to take a look at the code.

**Comment by nashmuhandes** [comment]
@Tormentor667 @Ozymandias81 ok I had some time to properly sit down and take a look at this.

As per my requested agreement for my involvement with TCOTD2 - please do not use any of my TCOTD2 code inside BoA. My permission only covers the Remaster projects and that hasn't changed.

My suggestion here is - use AFADoomer's ``SimpleActor`` class, and apply a camera distance shader to the fog sprites. It should be very trivial to write one

**Comment by Ozymandias81** [comment]
I have removed the attached file, and then I think we can close this since the shader implemented by @Talon1024 works like a charm for conelights. Just adding them for fog actors, but apparently nothing happens, probably the "coolness" sprite with "----" has a role in this (but also doesn't work for Steam so idk yet)
