### ISSUE TITLE
INTROMAP to INTERMAP music switch issue

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#302]
As some of you may have noticed, when we switch between INTROMAP and INTERMAP, we can hear the HQs song once map is loading for a while before the very first scene. The solution I guess should be not define a song from MAPINFO, but instead load it from map scripts always, but afaik that should break the JukeBox and some other music events when we return on HQs... Any feasible solution?

**Comment by Tormentor667** [comment]
Simply only load the music when entering the INTERMAP for the first time when it is set up after the INTROMAP

**Comment by Ozymandias81** [comment]
It is not that simple to fix I am quite sure, due to the nature of the music change script and some other stuff on map that should be verified. I will record a video when I can and post it here, remember that I have 4gb of ram and 1 gb video. Remember, test it as IPK3 and not from UDBuilder.

**Comment by Tormentor667** [comment]
I always test it from the ipk3 :) Maybe I can fix it if you if I see the problem

**Comment by Ozymandias81** [comment]
Here you are the little video, running under GZDoom r308.
[2020-10-24_00-44-15.zip](https://github.com/Realm667/WolfenDoom/files/5432056/2020-10-24_00-44-15.zip)

**Comment by Tormentor667** [comment]
I've watched it and I already expected that it was this situation. It doesn't happen for me though but I have an idea what's going on. The music of the INTERMAP isn't defined in the MAPINFO, all of the music that is being played is defined through scripts.

The main music is called by the "SetupMusic" script (line 871), the introduction music in chapter 1 is called with the "CUTSCENE_START2" script at line 2057. There are no delays between the script calles except that one line gets called after each other. This is no tic delay, but it's at least one line call delay. 

I can imagine that because of your computer, this delay is a bit larger until everything is loaded and therefore the lower lines at the bottom are executed later than the ones at the top. One think we could do is move the CUTSCENE_START2 script at the top, but I doubt that it will make any difference - but you could try that maybe.

@AFADoomer @Talon1024 maybe you can confirm this.

**Comment by Ozymandias81** [comment]
I just moved the Intro music call on CUTSCENE_START after the nointro check and it fixed the problem, probably I was just lazy XD
Thanks for the help @Tormentor667 !

**Comment by Tormentor667** [comment]
Youre welcome, thanks for fixing 💯
