### ISSUE TITLE
Potentially serious bug(?) with Gen. Miller

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#317]
After you finish watching General Miller's briefing, you can tell him you're ready, and watch the briefing again. I don't know if this was intentional, or a bug, but it could cause serious game-breaking bugs. I'd have to review the ACS scripts to be sure, but I haven't tested to make sure it's OK yet.

**Comment by Tormentor667** [comment]
Very good spot, funny that no one else was trying that before.

**Comment by Username-N00b-is-not-available** [comment]
I have seen this some months ago, but I did not think of this as a serious problem (instead I considered it an 'unplanned' feature, since if the player missed some slides they could relaunch the presentation and watch the slides again).

BTW @Tormentor667 the following has not been fixed yet, I can still use Miller from the direction of the door and block it from closing:
![Screenshot_Doom_20201210_110631](https://user-images.githubusercontent.com/59409713/101738854-cf959b00-3ad7-11eb-9f59-5c8d7a574bf8.png)
This is minor, but I haven't seen your opinion on this; should we try tackling this at all for now?

**Comment by Tormentor667** [comment]
I’d be happy to tackle it but I simply do not understand why it still can happen. I made the table block everything and use actions and you can still “use” the general

**Comment by Tormentor667** [comment]
So according to your fixes @Username-N00b-is-not-available this can be closed, yes?

**Comment by Username-N00b-is-not-available** [comment]
Yes, I think so. Just wanted to wait a bit until someone tests it on another machine.
