### ISSUE TITLE
Standard color for "top status messages" is not grey (\cC) anymore

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#329]
Noticed that the standard color for pickups and stuff shown as text message at the top screen isn't grey anymore (\cC) since we changed to the IPK3. Where is this setting set? Can this be set to grey again?

![2021-01-01_180527](https://user-images.githubusercontent.com/10298439/103443093-00db3400-4c5c-11eb-954d-3158726d0f40.jpg)

**Comment by AFADoomer** [comment]
There are cvars to set the print colors.

'msg0color' is for item pickups (Default is untranslated)
'msg1color' is for obituaries (Default is gold)
'msg2color' is for "critical messages" (Default is gray)
'msg3color' is for chat messages (Default is green)
'msg4color' is for team messages (Default is green)
'msgmidcolor' is for centered messages (Default is untranslated)
'msgmidcolor2' is for bold (sent to all players) centered messages (Default is brown)

**Comment by Tormentor667** [comment]
I wonder why is there a difference in choosing the DOOM.IWAD and the BOA.IPK3

**Comment by AFADoomer** [comment]
Maybe you changed the color for Doom in the past? These colors are on the hud options menu.

I also can't seem to set these values with DEFCVARS ☹️ .

'Untranslated' is the "proper" engine default, though...  Doom's font glyphs are already red to start with.

In clearing out my .ini, I was reset to use the OpenGL renderer instead of Vulkan, and the color grading shader leaves weird red artifacts around every edge....  Disabling that shader restores normal rendering.  Is this something others have seen?
![Screenshot_BoA_20210101_123145](https://user-images.githubusercontent.com/16618820/103444380-711e9100-4c2d-11eb-997c-85f75db62620.png)

**Comment by Talon1024** [comment]
I'm not seeing such artifacts. What GPU do you have? Are your GPU drivers up to date?

**Comment by MuadDib90** [comment]
I saw that line "Secret has been found" is now not gold, but that color you have on your pic.
I thought it is novelty in the newest GZDoom build... 
But as I see, this could be larger problem.

**Comment by Tormentor667** [comment]
I have never encountered such a bug. By the way thanks for fixing the messages.

**Comment by AFADoomer** [comment]
@Talon1024 - I'm on the latest NVIDIA drivers (15 Dec update).  Card is a GeForce GTX 1050 Ti. 

Issue doesn't happen when running with the on-board Intel card, so likely hardware-specific.  Odd.

**Comment by Tormentor667** [comment]
A new issue should be opened for this.
