### ISSUE TITLE
Some snowy artifacts when playing C2M1

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#339]
When playing Ausbruch, when you're behind the jail, you'll see these bushes which have lines above them.
Dunno if anyone can fix this ?

![Screenshot_Doom_20210125_140028](https://user-images.githubusercontent.com/77861029/105710907-0ef93900-5f18-11eb-8102-280b19597c55.png)

**Comment by Tormentor667** [comment]
This looks like an artifact that happens due to the bilinear filtering. That should be off by default anyway :)

**Comment by x3003** [comment]
These are set to linear. Turning them off would make them look really bad.

**Comment by Ozymandias81** [comment]
Thanks for your feedbacks @x3003 , but this is a known limit with shaders we have, plus graphics without filtera looks way better since it respect pixels shape and does the job for the desired 90's retrofeeling we aim for, as a Wolfenstein 3d inspired mod. Since this is just a taste related issue, I am gonna close this, unless someone is capable to fix shaders we have for these eveniences.
