### ISSUE TITLE
Mini game behaviour

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#374]
When you die in one of those mini games, you die 'for real', instead of returning to the main game.
Can anyone change this ?

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Sorry, which minigames do you mean? I do not understand. CxM0_x secret levels?

**Comment by Talon1024** [comment]
I think he means the Commander Keen levels (SM01, SM02, SM03)

**Comment by Username-N00b-is-not-available** [comment]
The cartridge gets used up in the process, you can't retry the SM0x secret levels multiple times from the intermap :-) That's because we would otherwise have to reset the secret maps to their original state. To change levels, we use ```Teleport_Map``` or something related, and it preserves the maps' state. If we had the SM0x maps in a different cluster, it would not be a problem, but other ones could arise with the state of the main game, especially the player's inventory. Or maybe we can make everything work correctly, we just have to find out...

If we accomplish this, a simple menu of 'Retry'/'Quit' on death in CK levels will also be very appreciated if it is possible to make, so as not to litter the savegame folder with repeated autosaves near the SNES in the intermap.

**Comment by x3003** [comment]
Yes, I meant the SM0x secret levels. If I know i'm gonna die in the secret game, I rather not play them, so I can get on with the normal game.

**Comment by AFADoomer** [comment]
Do you have autosaves disabled?  Out-of-the-box behavior is that you restart the current map after dying as Commander Keen.

@Username-N00b-is-not-available - Can't we just add the [ForgetState](https://zdoom.org/wiki/MAPINFO/Map_definition#ForgetState) property to the SM0x MAPINFO entries instead of taking the cartridge away?

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer We have some problems here... The INTERMAP state is also lost during transition. Maybe we can prevent this, I don't know how.

**Comment by AFADoomer** [comment]
It's not losing the state...  Spawned items, actor inventory, etc. are correct, but the scenery actors get changed.

**Comment by x3003** [comment]
> Do you have autosaves disabled? Out-of-the-box behavior is that you restart the current map after dying as Commander Keen.

No, it's off.

**Comment by AFADoomer** [comment]
What is the behavior we want here?  Dump players who die with autosaves disabled back to the INTERMAP so they can choose to restart the map from the conversation menu? 

Probably going to have to do some kind of hacky buddha setup to make sure that people who set disableautosave to 2.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Yes, let's not overcomplicate this like I did and just teleport them to INTERMAP.
>hacky buddha setup

In my reverted commits I used AllowRespawn in map definitions, could it be of use? A RESPAWN script could just exit the level afterwards... Or was it this what caused the INTERMAP state problems?

**Comment by AFADoomer** [comment]
That might work.  I haven't tested it.

The INTERMAP problems were caused because the RETURN script in INTERMAP assumes that the player is returning from a completed mission and sets up the NPCs and scenery as appropriate.

**Comment by AFADoomer** [comment]
This should be fixed as of dc2fe4902c8bc3c42b6e3311857f62589b6d15b3.  

Right now, the player will get respawned in the Keen map until they beat it...  Would it be better to force the player back to INTERMAP and make them manually restart the Keen map if they want to keep playing it?

**Comment by Username-N00b-is-not-available** [comment]
>Would it be better to force the player back to INTERMAP and make them manually restart the Keen map if they want to keep playing it?

Yes, I think it would be better https://github.com/Realm667/WolfenDoom/commit/b0f7bd9c4a6cd6b3d7105d3e20e213bb43d273fb, since a player without autosaves can overwrite their only save during the level, and they won't be able to exit it if they can't finish the level or get bored with it. This frustrated me a bit during my first playthrough.
Though this will now spam autosaves if they are on... Well I guess the player can just reload the Keen map autosave.

**Comment by x3003** [comment]
Seems to work now. But it would be nice if you went back to the intermap after a few seconds, instead of pressing the spacebar.
Beacuse if you don't press it, you have a black screen forever.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 So it is when you die in the normal game (except there is the 'You Died' message). This way the player can themselves decide what to do (reload a save or go to the intermap), if they can not open the menu in time. Though I don't oppose this suggestion, this way we can just use DEATH ACS scripts instead of RESPAWN ones. @AFADoomer, what do you think?

**Comment by x3003** [comment]
Well it's good as it is now, but would be better when you die in the mini game to fade to the intermap. Like when you woke up from a dream.
