### ISSUE TITLE
C2M6_C: Volcano skybox issues

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#393]
I noticed that the vulcano isn't as high as it was before when it was directly connected to the sectors where the player is moving in. Could it be, that the Z reference is not right anymore? I also noticed that the smoke and flare on top of the vulcano isn't visible anymore (thing type 21405 and 30002), most propably because they are in a skybox now. @AFADoomer @Talon1024 @Ozymandias81

**Comment by AFADoomer** [comment]
It looks like the z coords of the vertices got decreased too much when I scaled down the volcano to make it a skybox (the scaled down volcano looks squashed compared to the original).  Probably need to all be increased by 120% or so.

The smoke and flare are still there, but the smoke isn't as heavy because there are fewer actors spawning because of the particle handling and the flare is slightly low.

**Comment by Tormentor667** [comment]
Thanks for the fix, working as intended again 💪🏻
