### ISSUE TITLE
Something weird

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#416]
In C2M6_C, when you're in this building, when you shoot someone (1 or more ) between these doors.

1) The door(s) opens and closes all the time.
2) The bodies are moved up and dropped all the time.

But it only happens from the side seen in the pic. If you're on the other side, the door stay closed and the bodies don't drop.
Until you go through the door again.

![Screenshot_Doom_20210306_164012](https://user-images.githubusercontent.com/77861029/110212319-1c043300-7e9b-11eb-8ce8-2d12403cd623.png)

![Screenshot_Doom_20210306_163841](https://user-images.githubusercontent.com/77861029/110212328-29212200-7e9b-11eb-9d16-4176dda799ff.png)

**Comment by Username-N00b-is-not-available** [comment]
I seem to know the source of the problem. The sectors which contain the polyobject doors likely have large height (up until the outside sectors' one), so that the doors do not block actors on the floors above them, and the blocking settings for the doors' lines allow the dead bodies to end up on the doors.
I'm not sure of how to fix it, though. <strike>Well, that's what we get for using 3D floors for a multistorey building...</strike>

**Comment by x3003** [comment]
File for reproducing, using the latest git version.

[save17.zip](https://github.com/Realm667/WolfenDoom/files/6095841/save17.zip)

**Comment by Ozymandias81** [comment]
Maybe setting NOGRAVITY for corpses in that situation may help... gonna try something.

**Comment by x3003** [comment]
If also happens in c2m3, there's only no door here, just an opening.

![Screenshot_Doom_20210402_133110](https://user-images.githubusercontent.com/77861029/113517182-b29d4000-957e-11eb-9108-e738f081a7a0.png)

![Screenshot_Doom_20210402_133131](https://user-images.githubusercontent.com/77861029/113517189-b92bb780-957e-11eb-96a4-c131d79b308a.png)
