### ISSUE TITLE
todesritter impossible to fight

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#455]
In C2M5, the todesritter is almost impossible to fight. I had about 40 rockets, fired them all and it didn't do much damage.
The only way to kill him was to go in godmode and fire everything else i'd got.

![Screenshot_Doom_20210402_212641](https://user-images.githubusercontent.com/77861029/113455079-09cdd400-940a-11eb-9e82-59861c856c05.png)

**Comment by Wolfenburger** [comment]
Fire rockets one at a time. With bosses firing them fast cancels damage. I've noticed same stuff with the nades.

**Comment by MuadDib90** [comment]
Yes, this one is one of the toughest bosses, but still doable.
Yes, you have to avoid his line of fire, otherwise you're a dead meat.
That's why it is not "an arena" in classical sense (round one e.g.), but is more complex. You have to use your surroundings to your advantage to take him down.
Peek out, take a shot, cover. And again. (It's not suppose to be easy and quick. @Tormentor667 feel free to correct me here...)
And afaik he is not able to go down the stairs to lower level of the room, which also should help you. :)

**Comment by x3003** [comment]
Oh, I fired them one at the time, moving all the time from left to right and vice verse. But not as close distance as I'm showing here in the pic. Even at this distance I barely can hurt him w/ the leftover rockets. Here it took about 30 and it's not even showing 50% damage.

**Comment by Username-N00b-is-not-available** [comment]
@x3003, the Death Knight has huge metallic armour that protects him from explosion damage (specifically, [reduces it to one-fifth](https://github.com/Realm667/WolfenDoom/blob/a3a54b5661ebeb1ccdafd9bb1f177fc57a6abb22/actors/monsters/bosses.txt#L2605)), so no wonder you were not able to remove him from the face of Earth with rockets.
Use bullet weapons, you should have heaps of 9mm and 7.92mm ammo at this point. IIRC the ÜMG43 could even stun him. @MuadDib90's advice also applies, of course.

**Comment by x3003** [comment]
Such a waste of those lovely rockets :(
