### ISSUE TITLE
Can't buy armor

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#460]
After C2M5 / Astro, Rojas tells me he has a new armor (tesla shield). But when I wanna buy it, I can't. He says I don't need it.
I have enough cash, so that can't be the problem. And to my knowledge, I didn't picked up the shield in the astro level.

![Screenshot_Doom_20210403_215418](https://user-images.githubusercontent.com/77861029/113507477-fd9d6000-954a-11eb-8101-2f8864b50cc2.png)

**Comment by Tormentor667** [comment]
Assigned to @Ozymandias81 @AFADoomer @Talon1024

**Comment by MuadDib90** [comment]
> 
> 
> Assigned to @Ozymandias81 @AFADoomer @Talon1024

I think that's because the tesla armor is only up to 100 %. Yet you already have over, 139 % to be precise.
I think this could be resolved by giving the tesla armor the highest priority (when buying).

**Comment by Username-N00b-is-not-available** [comment]
> I think this could be resolved by giving the tesla armor the highest priority (when buying).

@MuadDib90 Sadly there is no such 'priority' in the base engine. For checking if the armor could be picked up or not (= bought or not, in this case), the game simply checks the current armor amount (139). It does not pay attention to savepercent or other armor properties. We can rewrite the armor pickup logic for our needs, possibly even something like the Quake system could be implemented, but I had already suggested changes in the armor system some months ago, and they were rejected as too complicated.

@x3003 How did you get 139% of Leather Jacket armor BTW? 🤔 Usual amount is 50, and you can only buff it up to 100 with Stahlhelms. Is it because of Astrostein armor shards?

**Comment by x3003** [comment]
Nothing special, just played astrostein and got some armor.

**Comment by AFADoomer** [comment]
This should be good to go after 0b119480d0095a25b3b65a4d40165c282333ea81.

Basically, after this change the SuperShield item can always be picked up unless you already have 200% SuperShield armor.

An alternate way of fixing this would be to re-work the armor handling completely so that you always keep the highest save percentage, and other pickups just add to your armor amount instead of overriding the save percentage with their own.  I have that coded, too, but I think it might change gameplaye balance too much.
