### ISSUE TITLE
Panzerschreck got moved

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#481]
In C3M1 the panzerschreck in the basement got moved to another place across the room. This makes getting there in the first place quite impossible. So can anyone place it in the original position, so this room is do-able again ?!

![Screenshot_Doom_20210415_221604](https://user-images.githubusercontent.com/77861029/114944931-c4b59300-9e48-11eb-8d89-bc160ba038e8.png)

**Comment by Username-N00b-is-not-available** [comment]
@x3003
Given the low resources available to the player, the battle is quite tough, for sure, but it is doable. Here are some tips for the fight:
- Get rid of the regular soldiers first, Mengele only fires "slow" projectiles and does not have bullet attacks.
- There is some health scattered over the arena, I remember dog food and field kits (one of them should be to your left).
- Increase gamma correction a bit, it will help you see the guards (you seem to already follow this advice :-) )
- Since there is very little ammo, use all weapons that are available to you. There should be a Kar98k in your inventory, it will one-hit kill the basic soldiers most of the time and deal good damage to Mengele.
- If everything else fails, save/load more.

You won't one-shot Mengele with a Panzerschreck anymore, by the way; and it is _not_ obligatory to pick it up, since the tanks you'll see in the map later could be destroyed with a flamethrower (if you manage to get it from flamethrower guards) and grenades (there will be plenty).

**Comment by x3003** [comment]
You forgot about the dogs, they cost a lot of ammo. The soldiers cost even more ammo. Mengele takes 2 panzerschreck + some shotgun / grenades. But getting to the (moved) ammo is the prob.
Later there are 2 panzerschreck reloads, so no probs there.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Why don't you use the shovel against the dogs?
Even if that, there are 3 dogs, I wouldn't say that it makes a lot of ammo. A dog has 20 to 30 health, MP40 damage is 9 to 14 per shot. This means you need 6 to 12 bullets to deal with them. They do not have ranged attacks, so you can wait until they come closer to make accurate shots if you absolutely want to avoid attacking them in melee.

> shotgun

Do you mean the rifle? Or have you returned to the Mengele basement after having acquired the shotgun?

Ah, I also forgot to ask you on whom you spent your ammo and grenades before the screenshot ;-) I had 148+32 MP40 ammo when I got to the basement (playing on Normal), two grenades, 19 Mauser cartridges. Do you use the shovel at all? It is quite obligatory to use it for some time, since it is the only way to save ammo on single guarding enemies.
As for the strategy, a good one may be to lure all the guards to the north of the brick wall (they will just go there by themselves if they spot you), wait for all dogs to get to you (killing them with the shovel), then make a sprint closer to the centre of the basement and throw a grenade at the stacked MP40 guards. You will take a few bullets, but chances are high that most of the guards will be caught in the explosion:
![image](https://user-images.githubusercontent.com/59409713/115020695-9c1eaf00-9ec3-11eb-98e8-690562c021e4.png)
You can also try to get Mengele stuck on a decoration, or repel him from coming close to you by holding a shovel, he understands that you are holding a melee weapon and is afraid of that ;-)

***
I've played C3M1_A to test the ammo balance, and I have some unrelated nitpicks:
- The "ausser Betrieb" sign is no more correct, you can use all ten levers from the tower.
- Why was the IBM sign on the scientists' console changed to Siemens?

**Comment by Ozymandias81** [comment]
The panzerschreck was moved there by me since I remember clearly that N00b and some other people said the battle with Mengele there was real unfair, then later again easy, but everyone lamented to have narrow zones to mover there and no real weapon to turn down Mengele in a feasible way. I am fixing that zone again, where now the helmet and the grenade near the panzerschreck will be present only at skill 1-2 (0-1), and also gonna readd the lever thing.

**Comment by x3003** [comment]
>Ah, I also forgot to ask you on whom you spent your ammo and grenades before the screenshot ;-) I had 148+32 MP40 ammo when I got to the basement (playing on Normal), two grenades, 19 Mauser cartridges. Do you use the shovel at all?

Well, the game shouldn't play in just 1 way, so multiple ways are possible of losing ammo ;) And yes, I use the shovel on a few ppl after entering the red door.

>ausser Betrieb

The außer betrieb sign should apply to lever nr 1, which doesn't work, not the other ones, I think.

**Comment by Username-N00b-is-not-available** [comment]
Don't expect to win in a first-person shooter if you are shooting crows instead of enemies :-)
IDK, all levers worked for me today (I'm using one of the newer commits), including the lever 1. Maybe it was fixed recently.

**Comment by Tormentor667** [comment]
Please keep the Panzerschreck where it was. You should find it down there but not instantly at the entrance of the room.
