### ISSUE TITLE
Add button hints?

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#483]
I was reading the comments section of the article GamingOnLinux.com recently ran on our release date, and I noticed one [particularly interesting](https://www.gamingonlinux.com/2021/04/wolfenstein-blade-of-agony-releases-chapter-3-plus-a-revamped-chapter-1-a-2-on-april-30/comment_id=201600) comment. It's basically saying we should tell the player which buttons to press as necessary, which is a good idea since some people playing this game may not have played Doom, or set up GZDoom with the required controls.

We should also keep in mind that some players may not have bound the required controls.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 This is a good idea! It can be done by HUDMessage(), see cast type ```k``` in https://zdoom.org/wiki/Print#Cast_type. Though it will mean that such messages will have to use another script instead of BoADialogue, since BoADialogue displays everything just as strings.
The basic controls are bound by default in the ipk3 version, by the way.

**Comment by Talon1024** [comment]
I was thinking of doing something similar to the hint text scripts on C2M1 and other levels.

**Comment by Username-N00b-is-not-available** [comment]
Yes, also a good option. Custom scripts are still necessary, since this hint text script is only able to show the virtual key names, not key bindings: https://github.com/Realm667/WolfenDoom/blob/c5e72be61d7ea767876cef023c00b153f426816f/source/messages.acs#L211

**Comment by DoomJedi** [comment]
..and we also had one youtube comment about us dumbing the game too much.

One comment against one comment, how you decide if to change anything?

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi Well, our party line seems to be 'explain everything twice or thrice'. There were multiple discussions on it even during the short time I have been following the repository, and it more or less stayed the same. There is no solution that will please everybody, but at least this one will allow less attentive players or less acquainted with Doom not to ragequit the game after running into a feature they did not care about.
Do you have a link to that comment and surrounding discussion, by the way? Could you please PM me on the forum with it?
***
I think I have another mutator idea, where nothing would be dumbed down anymore :-)

**Comment by DoomJedi** [comment]
"Been playing the mod since the days of the 0.95 beta. Can't believe it's been 5 years since then. Goodness me, how time flies.
While I'm quite excited on the release of the finale at last, there are a few concerns that boggle my mind. 

Particularly with things like the use of markerpoints to pretty much spell it out in bright yellow colors to the players instead of subtly telling them through use of indirect signs (for example, that wall in C1M6/Grabräuber by the lava hall with 3 separate map-based signs from arrow on the floor, light on the wall, and a big X on the switch yet still adding a markerpoint on top). Will Chapter 3 have more of that or less of that? Or perhaps a way to enable/disable them? Idiotproofing's all fine and dandy until you start treating all players like they're all blind imbeciles, zero trust on our part to find our own way."

**Comment by AFADoomer** [comment]
I think @Username-N00b-is-not-available's idea of having this as a mutator is the way to go.  

We *could* also just add a CVAR toggle option that removes specific exclamation mark indicators and stops chests, safes, chest keys, etc. from being drawn on the compass.

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer Why would a player even use the compass at all if they hate being given hints? The world axes are shown on the automap.
Here is the most straightforward way to implement the mutator: [disable_hints.zip](https://github.com/Realm667/WolfenDoom/files/6325787/disable_hints.zip), it replaces all exclamation-type sprites with blank graphics, removes secret hint papers and disallows compass usage (in a crude, but effective way: it just kills the compass event handler).

Anyway this issue got derailed too, sorry for that @Talon1024 :-D

**Comment by Ozymandias81** [comment]
We mustn't satisfy everyone's desire remember, this is OUR vision of the mod and it got be already changed a lot from where it should have been. That dude is also known to pop up some quite pointless criticisms, most notable on ZDForums.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 Could you please tell me whom is DoomJedi talking about, or just the link to that comment? Just want to know.

**Comment by Ozymandias81** [comment]
He is ZikShadow comment on BoA Chapter 3 trailer, he is a good spriter but usually not kind with words.

**Comment by AFADoomer** [comment]
Is anyone working on this already?  If not, I can easily extend the current HintMessage script to take another parameter for the bound action and print the key bind information.

**Comment by Talon1024** [comment]
I didn't know what the consensus on this was, so I wasn't working on it. However, I am working on it now. I'm adding a new script to messages.acs.

**Comment by AFADoomer** [comment]
I have done it already.  Please don't do any more...  I'm most of the way through scrubbing all maps to use the same script call for hint messages.

**Comment by AFADoomer** [comment]
Implemented in d0fca55ff3cc8fdf10cc5d5b8466ad89ae621288.  Functionality is in place, but I've only updated the C3 maps and intro/intermaps in this commit, pending the polyobject line updates for C1/C2.

**Comment by Tormentor667** [comment]
If I have seen it correctly you are done by now?

**Comment by AFADoomer** [comment]
Yes.
