### ISSUE TITLE
Doors won't open enough

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#486]
When you fire too early, these doors won't open enough, so then you can't get in.

![Screenshot_Doom_20210417_075035](https://user-images.githubusercontent.com/77861029/115106052-dd19d080-9f62-11eb-8a65-9c7f7cb2ae5c.png)

**Comment by Ozymandias81** [comment]
I alwasy thought if it was possible to add a user_ property to tanks that when they die, if the user_fade property is true, their destroyed counterpart will fade in place after a couple of seconds. This was my original thought to fix this issue ages ago, but never had the chance to make it work due to difficulties to transfer said property to destroyed variant... The best I can do is to create a separate destroyed variant which fades itself, including an additional tank variant too for it.
What do you think @Talon1024 , @AFADoomer and @Username-N00b-is-not-available ?

**Comment by Ozymandias81** [comment]
Well working on an easy approach which doesn't require a new actor, directly on map
