### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#501]
Dear friends,

a little more than one week is left and I thought it is the right time to dedicate some words to everyone involved here, especially the supporting team and the core team. 

A long journey lies behind us, a long journey that ends on April 30th (or maybe not, depending on the bug reports of those people out there, but let's hope they don't exaggerate). When I started the project over 6 years ago, I had absolutely no idea, where this is leading to. Maybe I wouldn't have even started the "coffee break project", the little WolfenDoom inspired mapset, that I had in mind, if I knew how much work and time this is going to draw.

On the other hand, I would have done it again when considering how much fun I had working with every one of you, how much I have learned when it comes to game design and that I earned new friends - yes, I consider you a special circle of friends after such a long time.

We didn't only share the passion for this mod, but we also shared funny moments, we shared strokes of fates in our families and we shared a lot of our private life (especially those active in the Facebook chat know what I mean). It was an amazing journey, it really was, and we reach our final destination in a little more than a week.

I am curious to see what happens after the release, I am very sure, that this will be a special footprint in the history of a "amateur standalone games for free". Some people out there have already described it: It feels more original than younger Wolfenstein releases, it feels like an official product, a sequel to Wolfenstein 3D - and that's what it is. We made a top product in so many aspects, we brought modding for Doom to a totally new level and I am so proud of our creation.

Thanks to everyone of you for being so talented, friendly and productive people, thank you for making these 6 years such an exciting time that brought me so much fun and creative moments, thanks for turning this into the greatest and most entertaining project, that I have ever worked on.

And now: Open a few bottles of beer and let's celebrate the final week of development. We deserved it so much ;)

Sincerely,
Dan

**Comment by DoomJedi** [comment]
A bit of my own retrospective here.

This is PM from April 2016 that started my way with BoA:

> Usually I don't contribute to projects of others and prefer my own (and I'm a busy modder).
> But for projects that look to me epic enough I feel honored to be allowed to contribute.
> And this is great modding, so much planning, detail, so much soul put into it...it's not a "lazy" mod (as I call such...).
> 
> But again, only as far as my free time will allow. While progressing on my own projects.

...What impressed me the most in BoA is the bullet hit reaction making you feel like being hit by real bullet, and those bullet tracers....

That was Torm reply:

> Hey Doomjedi,

> first of all thanks for your offer. We'd be happy to have you onboard if you have time and interest. ...

And then my way with BoA started. 
At first I thought it's something very limited for short while, but then things developed into a whole new direction. 

First it's a good time to thank to Dean twice.

Once - for speaking for my candidature to Torm, who was not familiar with my prior modding work (especially for me being much less active in Doom community for little eternity - left for the Wolf3D one). 
For admiring my past works, even if controversial to some. Also allowing me this...closure to the past trauma, closure with a feeling of good classic revenge :)

Secondly - for the "double resolution" idea and belief. I always felt the low-res guards looked silly and cute, but I would never imagine something can be done about it, and by myself, who is more 64x64 Wolf3D spriter than anything else. It looked straight out impossible. When it was first proposed by Dean - we all felt it's nuts, really crazy idea.  And I wasn't even aware of full art scope of BoA at the time.
But somehow he believed in it so much, and even proposed specific concepts, tricks and tools to make it happen, to make it feel manageable.
And we all know the result. Big thanks to Dean for that.

At first when I joined the project - I thought it's mostly to contribute art from [that] game, for one of BoA levels. That was it.
And then Double-Resolution project came in and made me stay and work hard for years, with many other tasks coming along and contributing to many gameplay ideas, many of which come from my own mods.
Sleeping soldiers - came from my "Green Arrow" mod. Half-dead guards, cleaver throwing mutants and others - came from my other mods. Ideas like rolling and headshots sure are inspired Brutal Doom, but were used before in my mods.
Was happy to contribute to russian-related Easter eggs as well, including idea for a secret level.

Now I feel it made a fantastic artpack for future modding to come - both in Doom and in Wolf3D modding communities.
Most epic mod or longest future legacy I took ever part in.
It was also fun for me to return being more active in Doom modding community, coming out of my Doom-retirement. It inspired me to contribute to "Project Brutality" afterwards and even discover my art on Brutal Doom which gave me epic BD credit.

[to be continued, probably...time to go, my wife calls me]

**Comment by MuadDib90** [comment]
Hi, Tomas here,

I'll glady join too for a few words, if I may.

I will start with something you all may find interesting, I guess. Back in 2015/2016 (not remembering corectly anymore) I searched for new WADs to play, kind of celebrating my successfull graduation at university in Brno. When I am thinking about it now, one of them was BoA, not knowing its potencial back then, and in what it wil become. I tried to play it, but my laptop back then was not really one of the cooperative ones, in means of performance. So I could play it only on lowest options, and the funny part was I thought it was some kind of joke... because I "couldn't get out" of the intermap. I didn't know I needed to go to gen. Miller to be able to proceed to another map stage. I wasn't simply used to that mechanics at that time. So I put it off...

Many years have past since then, many reruns of the series such as Star Gate, M*A*S*H (even Dallas, my goodness!) went on Czech TV, and by this point I totaly forgot there was any BoA at all.

Then, one lazy Christmas Eve, I searched through Doom wads again, to see any news (and new wads to play) in Doom community. And it happend just like to many others out there. Love at first sight. I grabbed it in the time of the second episode release. When playing, I encountered for the second time in my life, THE deja vu, in my gaming history. (The first one occurred when I was playing Half-Life 1 by myself for the first time - two years after the official release - realizing that this is the game I was only looking at at friend's place back then.) When playing BoA at this point, I got chills on my back similar to that from many years before. Just like to be a child again - it was unforgettable and joyable feel.

It didn't take long and the invitation for localizations were out. This was my chance I took. To help you, to help myself, and to do something minor for Czech players out there too. Looking at it from now, it helped me a lot to grow in my writing skills - although it may seem strange. Now I am really glad I was able to help even more in some aspects - not just a blind translation (with no offence to any other translators). Considering I was part of the supportive team only a half of the year, the more intense and joyous it was for me.

I said it many times before, and I have to say it again: I am impressed, what a "bunch of friends" can do - not mentioning the differences between them; mainly language, physical distance, nations from all around the world. - It almost looks like with passion and understanding you can do whatever you want to, with whoever you want to. - It warms me to be considered as "one of the friend of this bunch", than I could "met" you (what an internet allows), to know you all. As Dan said, especially those on FB chat. That means a lot to me.

OK, no more tears... I am reaching for my glass now.

Yours,
Tomas

**Comment by Ozymandias81** [comment]
Thanks Dan, and also all team core members, I wish we had an infinite time amount to create tons of mods al together, with the help of our supporting team... but damn, 6 years have passed even for me in this mod, and I was practically a newbie once Torm decided to contact me on ZDForums that 15 february of 2015, after he noticed my work with Batman Doom: Reborn and Gore.
It felt for me an incredible honor to contribute on a Tormentor667 project "wow", since UTNT and Stronghold made me want to enjoy the modding scene and to improve Doom and similar games experience using my fantasy through decorate code... But with BoA development it has been such a loong train, I mean: I have master quite everything from decorate, thanks specially to MaxED and wildweasel base code, which I managed to transform into something different and that felt "enhanced", specially on Chapter 1 release. Then during Chapter 2 development, my skills and inspiration improved so much: 3d models ripping and editing, resources organization and optimization, any questions I had regarding this that it always magically appearead and fit with the overall mod consistency; suggestion for a couple of effects, tons of enemies variants (mainly thanks to Doomjedi and DoomJuan, which with their art and creativity we mixed up probably the largest amount of variety of foes for a Wolf3d inspired mod ever), sounds research, project optimization (the best on has been once I have discovered how to improve trees performance even before the DistanceCheck feature, which from there obviously happened after a request bu Torm himself on ZDF), massive use of Slade and external editors for countless things, manual editing of sprites for little adjustments via GIMP, over 6000 brightmaps done first in black/white and then, after the hi-res decision, colored ones to emphasize some details (and it is really noticeable with undead enemies, which makes justice to incredible dedication from DoomJedi for them)... I can't even stop how many things I have learned concerning Doom modding with BoA, I have contributed to BlooM (and still doing), to awesome projects such as Project Osiris 0.9, Brutal Wolfenstein 4.5, Quake 2 TC Project, submitted tons of textures packs on Realm667, some props and a couple of enemies, which have also been added on later re-releases or cool R667 glories such as TCOTD1 and 2.
I merely can stop writing with a proper punctuation here, and then Chapter 3 release, which is going to happen, has been probably something that won't hapen again in the modding scene. We added so much to the project, always in a mutual work, that you can barely recognize it from what it was during Chapter 1, this tanks also to AFADoomer and specially the awesome polishing done by Talon1024, which is one of the coolest guy in the modding scene. We are also lucky to have N00b and MuadDib90, that they helped us to speed up the final process of debugging, playtesting and improvement of the whole mod, or better "game" I would say.
I will never regret that day when I started doing some gldefs for Batman Doom, to improve EdTheBat fixes for the vanilla edition of the original mod: because it is there where I started to follow Dan suggestions regarding GZDoom editing related stuff, and I am so happy and sad at the same time that the reason why all this happened, why all this has take form and shape, is gonna happen in 8 days from today.
Whatever will be people response, it will always matter for me what we have done all together me, Torm, DoomJedi, DoomJuan, Talon, AFADoomer and the supporting team (specially maxed, Tau and N00b), in these years, won't happen again okay, it has been a very complicate thing, sometimes frustrating and full of personal issues, but damn it has been so much fun that if someone would tell me "hey, wan't to go back time and repeat it from the start?" I would totally say "oh shit yes, I am psyched to redo this again!"
Thank you very much everyone, it is not easy to write something proper for what happened in me these 6 years together, but I have to thank you a lot and I will be always happy to have find some true passionate friends in the world of modding.
I am sure that one day most of us we'll meet up in person, and I will be one of them: GRAZIE RAGAZZI! :heart:

**Comment by Username-N00b-is-not-available** [comment]
First of all, I would like to thank the team for deciding to make Blade of Agony more accessible to the various national parts of the Doom community by providing translations. If it were not for a translation advertisement by DoomJedi on the Russian Doom Community forum, I doubt I would have paid attention to the final _development_ stage of Blade of Agony, because I simply would not have anything to offer the team. "I have never been a good map designer, or a programmer, or a graphics artist, so why would Realm667 even need me?" A translation into Russian seemed a fitting way to contribute, and I also would not have been doing double work. I think the initial speed of my translation work might also have encouraged the other translators a little bit ;-)

Soon the supply of empty lines in the CSV ended. I could just have disappeared after that, I was more or less free to leave after doing my part of work... but could I have done that?

I had played the first chapter in 2016, then the second one after it was released. What I noticed then is that Blade of Agony was a project so different from Doom mods, a full total conversion with great visual and gameplay variety; strict polishment and a set of common level design rules; elaborate maps, script/code and artworks.

There are lots of Doom projects being released all over the world, now more than ever, but honestly, neither of them could attract me comparably to how Blade of Agony did. Most of things done nowadays seem so unprofessional that I cannot fathom how they are able to gather whole crowds of fans around them — and not only of 14 year old fans. (Though maybe that's just me getting old, way ahead of time.) This is especially true for ZDoom projects, namely copycat gameplay mods which always seem to 'invent' the same primitive story, replace weapon sprites with some game rips, and enemies with ones directly taken from Realm667 Repository. This is just like what was done in the 90's via DeHackEd, but on a new technical level. The stage of quality control does not even seem to appear in the process; things plucked from various previous releases just quickly get thrown into the pan, spiced with a few 'special features', and the result is called a brand new release... (It seems here I came quite close to talking about the state of the contemporary culture as a whole, but this likely does not belong to a congratulations thread...) The majority of the community forgets such 'releases' after a few months, if not weeks.

Blade of Agony, on the other hand, has a solid design philosophy and quality standards. This would already have been enough for it to stand out from the crowd of silly mods, but the dedication of the developer team establishes the special status of the project irrevocably. So much free time was spent on writing the code for the actors engaged in the scenes and for the interface, converting and adjusting resources, thinking over and improving the plot and in-game texts, drawing graphical art, designing map blueprints and implementing them... Considering also the skills of the developers, it was obvious for me that Blade of Agony is bound to have success. I also like the WWII theme way more than space marines in generic techbases or more extreme fantasy, so this was a great factor, too.

While helping the Realm667 team during this year I learned to do a lot of things, not all of them efficiently or with high quality :-) , but I think this experience will really help me in life afterwards. It also made me realize how much effort it takes to create something really worthwhile; I am very grateful to the team for that. I have decided to get out and move on with life: since the Doom community seems to be oversaturated with releases, it would be too much time spent for too little outcome (if any). (This decision was made before Tormentor667 decided to announce his retirement, just to be clear.)

It was a great honour for me to work with (and for) the Blade of Agony team. I really admire the effort of a small group of people who were able to build a project of this magnitude in their free time, motivated only by player reception, and I wish you all best luck in anything you choose to do afterwards!

Yours sincerely, "N00b"
