### ISSUE TITLE
I need a couple of questions to be replied from main Team in order to complete an interview I am doing for safarigames.it

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#520]
Dear friends, as the title says, I need a couple of questions replied from you so I can write down the sum of our ideas to give the writer a mutual reply. So please @Tormentor667 , @Talon1024 , @doomjuan , @DoomJedi and @AFADoomer I need you to write down your replies here, which I'll summary as a mutual answer in italian language. I need it for tomorrow mostly, so in case I won't have all, I'll consider the ones present at least and write down the reply. Thank you very much :smile: 

- It seems that "old school" shooters, both singleplayer and multiplayer, are finally making a comeback, what do you think?

- Do you have projects for the future?

**Comment by DoomJedi** [comment]
"Do you have projects for the future?"
For now I'll get back to focus on my Wolfenstein 3D mods. Currently working to finish deathmatch edition of my "SplitWolf" mod (Splitscreen Wolfenstein 3D). For the first time players will be able to challenge each other in deathmatch mode on specially-made DM maps (with ability to add custom maps), with some new weapons and features, while still keeping the classic feel.
Meantime I will keep following Doom modding community to find projects I might be interesting in participating.

"It seems that "old school" shooters, both singleplayer and multiplayer, are finally making a comeback, what do you think?"
It seems so indeed, success of "Ion Fury" was big surprise for me to be honest, but there is special charm for oldschool shooters and retro gaming in general. Retro - never really goes old, in gaming, fashion, or any other area. The more we move forward, the move we miss the past and its charm, it seems like makers of old games knew some secrets we've forgotten in a rush for monetizing and big gaming corporations. Simplicity, core focus on gameplay and not the visuals, pixels that engage your imagination rather than forcing external vision upon you. The more you are invited to imagine, the more of yourself you put into the game, the so more interesting the game becomes for you - as it becomes a game about you, your world and vision you've spilled onto the game. And we are always the most interesting persons for us, heh. Such games engage us more than over-detailed creations that look imposed upon us.
Also - lets not forget the retro specs, suddenly all can afford a run a game in good fps, rich and poor. 
New retro games are not fully retro - just in style, but what makes them so appealing - is that they accumulate all the prior, modern game experience, like a final exam at gaming design school, after generations of game makers learned all they could about level design, to perfection. 
Retro style also adds fun limitations that boost creativity forward trying to overcome them or making them unnoticeable. Most creative things I've seen in gaming were made under the worst limitations one can imagine. As limitations give the creation a meaning - be is engine limits, costs or time. As it's not a big deal to create good stuff under unlimited time, engine and budget.
To do more with less - it's the core fun of modding, and game making in general, at least for me. Good developers know to make more with more - but only Gaming Masters know to do more with less, and that's a charm of retro games development.

Also, modern games became were complicated to get into, with tons of features and long tutorials.
People are looking again for games you can just pick and play, start playing right away, and retro games do just that, they are just pick and play type of games. Games focused on pace and gameplay.

There are fantastic indie retro-styled games, Celeste and Shovel Knight just to name a few. There are fantastic retro modding communities, like "Commander Keen" modding community which helped us with BoA at some point. Wolfenstein3D, Doom, Duke3D - all have fantastic modding communities that are alive and kicking even in 2021.

**Comment by Talon1024** [comment]
> * It seems that "old school" shooters, both singleplayer and multiplayer, are finally making a comeback, what do you think?
Over the past 10 years, we can definitely see renewed interest in "old-school" boomer-shooter FPS games, mostly on the indie side of the game industry, but also from some AAA studios. People these days still play the video games they loved in their childhood, using either emulators or source ports.

Some games like Doom, and the myriad of games based on or inspired by Doom, allow players to create their own levels and other content for the game, and thanks in part to that, there are large dedicated communities which put out new content for these old games all the time.

In recent years, we've seen a lot of new "old-school" style games being released, and not only first-person shooters. On the indie side of things, we have games like Ion Fury, Hedon, WRATH: Aeon of Ruin, Dusk, and several others. On the AAA side of things, id Software/Bethesda have released DOOM, DOOM Eternal, and Quake Champions, and they've even re-released Doom 64. One major event focusing on old-school shooters was Realms Deep, wherein many new old-school shooter games were announced, in addition to updates or expansions to existing games. So there's definitely a market for such games.

> * Do you have projects for the future?
I'm hoping that putting "Worked on Wolfenstein: Blade of Agony" on my résumé will boost my career prospects within the industry. Aside from that, I'm hoping to create an indie game or two of my own.

**Comment by Ozymandias81** [comment]
Thank you everyone, going to type down the interview since it needs to be write down in time for release. The article will be added on BoA website when it is out :sunglasses:
