### ISSUE TITLE
Friendly forces have problems moving

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#524]
In c3m5_a, the friendly forces have problems moving around these 2 spots. The legs move, but they don't really wanna follow, as if they were captured by these spots.

![Screenshot_Doom_20210427_134703](https://user-images.githubusercontent.com/77861029/116236436-5c778300-a75f-11eb-9d3b-8ee0616d5286.png)

**Comment by Ozymandias81** [comment]
Since we plan to release BoA with gzdoom 4.6 r195, please only with it. I think the issue here anyway must be related to custom user_ vars set for those actors or that maybe they are at 0mp on map, there was a similar issue on c3m2 with AlliedSoldier derivate actors placed on map, I had to set them at 16mp height to avoid this behavior (because they gets activated/deactivated)

**Comment by Ozymandias81** [comment]
Btw noticed that those soldiers have.... -30 health?!?!
![image](https://user-images.githubusercontent.com/11136108/116281957-85f9d400-a78a-11eb-96fb-9144169c76e7.png)

**Comment by AFADoomer** [comment]
Per UDMF spec, negative values set health amount directly, positive values multiply the default health value.

**Comment by Ozymandias81** [comment]
Lol but what's the sense on have 30hp soldiers? I have set them with 1, but everyone is free to revert that by editing the map.
Anyway, the Reichskanzlei road zone is really unplayable that's true... I tried no clipping in the sky for a while looking to the long road and I had EffectsManager at 156.0 which is huuuge value, I also noticed that not only debris flood EffectsManager, but the msot responsible one there are also tracers.

**Comment by x3003** [comment]
They still have a hard time following w/ the latest git version. But when you reach the last building before you meet the russians, they suddenly come. And later on when in the building w/ goebbels and so, they have a hard time following, again.

Here are they dancing again. Well the war isn't over, so come on guyz.

![Screenshot_Doom_20210427_202117](https://user-images.githubusercontent.com/77861029/116296813-f27ccf00-a79a-11eb-8419-d9031683257c.png)

They really don't like this street.... They are were my pointer is.

![Screenshot_Doom_20210427_202844](https://user-images.githubusercontent.com/77861029/116296957-1b9d5f80-a79b-11eb-8cbf-9291c56173a6.png)

**Comment by AFADoomer** [comment]
Almost looks like the flat sprite blast marks are causing navigation problems.

**Comment by Ozymandias81** [comment]
It doesn't happen under r195

**Comment by x3003** [comment]
> It doesn't happen under r195

Yes, it does. I've tested it w/ r208, but i'm now on r195 again.

**Comment by Ozymandias81** [comment]
I wonder... I didn't touch rendering distance, only PPShaders off... and I see you have fog off, which are your overall settings when you play BoA? Mind you I have tested it via UDBuilder loading directly the map from there.

**Comment by x3003** [comment]
This must be one of my fav maps, so I've played this map quite a few times, always w/ fog off. And most of the time Ascher pretty much always follows. The other soldiers always died quite fast, so it's good they don't right now.

**Comment by Ozymandias81** [comment]
I' ve seen already that some maps and actors had issues with fog off. Could be that @AFADoomer ?

**Comment by x3003** [comment]
Tested some older builds, the version from 23/04 was for me better, they followed more, not always but do-able.
The one from 24/04 is a bit worse. So I don't know what changed between these builds.

**Comment by Ozymandias81** [comment]
Uploading a video to show you that it works under ZGDoom 4.6 r195 with latest build of BoA

https://drive.google.com/file/d/1QBdmPi0MUHJEl1ldRADF6syejJfO6nhF/view?usp=sharing

**Comment by AFADoomer** [comment]
The PlayerFollowers don't do anything with the fog levels (or the culling code).  I'm not sure why this is happening.

**Comment by x3003** [comment]
Making screenshots from the options don't seems to work...
Vulkan, not opengl.
Fog is off
In eff settings all density is max.
In rendering settings fov=94, last 4 options = 8192.
In post process, same, except bloom eff = off.
In Texture options, most are on, iso set to 16x, linear. Resize = off, NormalNx.

**Comment by AFADoomer** [comment]
Part of this was a mapping/scripting oversight.

The SecActEnter object in front of the door of the Chancellory runs the "MESSAGE_BEFORE_CHANCELLORY" script, but it was set to also be activated by projectiles (DORMANT flag) so could fire early and would deactivate the soldiers wherever they were standing...  The script should have only run when a player entered the sector, and the PlayerFollowers shouldn't just be deactivated (they need user variables changed to hold their current position and stop the player from re-activating them).

The second part was that the PlayerFollowers were trying to avoid mines, and that was wreaking havoc on their pathfinding.

Both should be fixed in 617147de038d149e9f8e955b29fedf1264be31d7.

If this doesn't resolve the issue here, I may need to put a cap on the fear timeout for the PlayerFollowers.

**Comment by x3003** [comment]
It doesn't look too bad, as they are following again.

**Comment by AFADoomer** [comment]
So can this be closed?
