### ISSUE TITLE
Boss isn't firing back

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#537]
In c3m5_a, Göring suppost to fire rockets (or something else ?), but he doesn't do anything except walk towards the player.
This makes him an easy target, unlike goebbels who is quite hard to defeat.

![Screenshot_Doom_20210429_195959](https://user-images.githubusercontent.com/77861029/116597707-3cde8700-a926-11eb-80bd-c11d01f18cc5.png)

**Comment by Username-N00b-is-not-available** [comment]
Does not happen for me on skills 0 and 2.
Though `GoeringProjectile` (a slow grey rocket which shoots a barrage of fireballs into many horizontal directions) can easily be destroyed with player shots. I thought this effect was intended; @Ozymandias81, what do you think?

**Comment by x3003** [comment]
I've played this map quite a few times (on the lowest level), but suddenly he doesn't shoot anything anymore.

**Comment by Username-N00b-is-not-available** [comment]
@x3003 Why do you use Freedoom 2 for testing? Blade of Agony is already an IWAD, no additional data is necessary.
Here is what happens for me with your savegame:

https://user-images.githubusercontent.com/59409713/116603805-06106d00-a936-11eb-8bc1-92ccb23a3e31.mp4

**Comment by Ozymandias81** [comment]
I watched the video and I don't see any issues, the rocket is intended to fly slowly, it gets faster as you raise skill though (at elast that's what I remember. While I doubt using Freedoom may alter something in this occasion, N00b said anyway something right since we playtest the mod in the same way as it gets released, which means not many alterations to default configuration and no usage of iwads or external mods, in both cases we aren't responsible of issues that may occur.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 I meant that you can shoot down the rockets (and it would often occur even without prior player knowledge), was it intended?

**Comment by x3003** [comment]
I've tried it a few times and he wasn't firing and I could easily shoot him. Now i've tried it again and now he fires. Dunno why, nothing has changed.
