### ISSUE TITLE
ENDC2 graphic needs correct uniform for BJ

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#559]
I noticed that the ENDC2 graphic isn't using the right uniform that BJ is using since our update. @DoomJedi can you take care of that? It's located in **Wolfendoom\graphics\intermission**

![endc2](https://user-images.githubusercontent.com/10298439/116811697-d0909d00-ab4a-11eb-8ca9-cb009796ada8.jpg)

**Comment by Ozymandias81** [comment]
I have added necessary resources on our dropbox folder too, check inside ..\Sprites\Hi-Res\Hi-Res (1nd, finished work from Maxim, needs naming and preparing by Virgilio)\Intermission Fix

**Comment by DoomJedi** [comment]
Can you recolor the uniform?

**Comment by Username-N00b-is-not-available** [comment]
I can try...

**Comment by Username-N00b-is-not-available** [comment]
@DoomJedi Here is a downscaled+recolored version of BJ:
[recolor.zip](https://github.com/Realm667/WolfenDoom/files/6411554/recolor.zip)
Could you please add shoulder straps to him?

**Comment by Ozymandias81** [comment]
Well check this, you can add stripes here if you want, was working on it.
![endc2](https://user-images.githubusercontent.com/11136108/116817226-9da7d280-ab65-11eb-95eb-3a2c7a77452e.png)

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 Could you please take a 640x360 png screenshot of this place in C2M6_C which is on the background and post it here? (I can't do it myself for now.) I would like to get rid of the compression artifacts on the background, but it would take me too much time to remove them manually.

**Comment by Ozymandias81** [comment]
Well you can simply apply the original image over the modified one but not over BJ, or Torm can improve it later.

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 There are artifacts near the border of BJ...

**Comment by Ozymandias81** [comment]
The original image has been done by Torm, and it has been converted into jpeg. Now I have recolored green colors from a converted jpeg to png (the graphics we have on BoA exactly), and I do see artifacts but my suggestion would be to mix both images, since we are atm okay with version we have already but which needs recolor and details. Torm didn't say to replace the whole image and remove artifacts, I didn't do that.

**Comment by Ozymandias81** [comment]
Better now?
![endc2](https://user-images.githubusercontent.com/11136108/116818401-663c2480-ab6b-11eb-9c34-602239b1b52e.jpg)

**Comment by Tormentor667** [comment]
At worst case I can check for the original file and we save it as lossless PNG instead of JPG

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 This honestly would be the best solution (if you still have the computer you created it on). The file date should be Jan 7, 2016.

**Comment by DoomJedi** [comment]
I made a sprite on dropbox a few days ago, but I guess noone looks there and just put in whatever work by whoever.

**Comment by Ozymandias81** [comment]
Well I didn't check the folder after n00b proposed to work over it, and I thought it was fine to not stress you for this reason specially since you had a busy week @DoomJedi ... So let's see, I'll reopen this and drop the zip with the necessary image here, can you adjust again the image hen @Tormentor667 ? Or consider this closed again ?
[N00bx1.zip](https://github.com/Realm667/WolfenDoom/files/6436040/N00bx1.zip)
