### ISSUE TITLE
Changing the "pain" redness from "overlay" to "color"

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#560]
I have wondered already several times, if the red color that fades the view if you are getting hurt can be changed to coloring the view instead, keeping the contrasts but teinting them red. 

Example screenshot:
![hurt](https://user-images.githubusercontent.com/10298439/116812297-67128d80-ab4e-11eb-8a35-ace0daafcec0.jpg)

**Comment by AFADoomer** [comment]
Something like this?
![Screenshot_BoA_20210502_171923](https://user-images.githubusercontent.com/16618820/116829666-99ca7f00-ab6a-11eb-9f77-24571f084870.png)

This is at the darkest (highest damage) level...

**Comment by Tormentor667** [comment]
Yes exactly

**Comment by AFADoomer** [comment]
Ok.  Need to do some more experimenting before I commit...  The damage fades are all in native code, and the variables I have to change in order to keep the engine screen flashes from showing might control other things (e.g., I'm pretty sure the ouch face is broken in my current code).

**Comment by Tormentor667** [comment]
Impressive that this is really possible.

No idea if my brain tricks me but I can remember, that something like this was possible in vanilla Doom.

**Comment by Talon1024** [comment]
> Impressive that this is really possible.
> 
> No idea if my brain tricks me but I can remember, that something like this was possible in vanilla Doom.

It actually is. Different levels of pain used different palettes, and one could use a "multiply" or "hue" filter instead of an "overlay" filter to achieve this effect in vanilla Doom. Of course, applying such palettes to modern hardware-accelerated Doom source ports would not have the same effect compared to vanilla Doom, since it works differently; you'd have to change the source code to modify the effect to your liking.

**Comment by Tormentor667** [comment]
Thanks, I knew my memory does't trick me :)

**Comment by Tormentor667** [comment]
Just wanted to ask if this is still being worked on.

**Comment by AFADoomer** [comment]
Yes, but still needs tuning.  

Works fine for normal damage types with minor hackiness (alpha for damage types in the player class all have to be set to zero), but once you start dealing with poison, the screen flash color is completely hard-coded (the dark green screen fade) with no easy way of canceling the fade without breaking the poison effect (and I'm still working out a way to not change the screen tint due to poison damage).  I'll commit my working branch later today.

**Comment by Tormentor667** [comment]
I am looking forward to that. Would it make things easier to apply the same effect to different damage types?

**Comment by AFADoomer** [comment]
Is the effect as implemented currently good?  Any feedback?

**Comment by Talon1024** [comment]
IMO, the effect needs to be stronger. The previous red overlay gave a much better impression of sharp pain than the current effect. Also, don't forget players can set the strength of the red pain overlay in the display options.

**Comment by Tormentor667** [comment]
Yes, maybe a bit stronger (threshold), but overall I really like it.
