### ISSUE TITLE
Crosshair is off

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#562]
From the start, de **default** crosshair is set to off. Could this set to on ?
Why ? With the crosshair on makes playing that much better.

**Comment by Username-N00b-is-not-available** [comment]
I think it is off by default for aesthetic reasons.
The crosshair option is not removed from the main options menu, you can activate/deactivate it any time you want.

**Comment by mcphail** [comment]
Flicking through the youtube videos which have been uploaded recently, many more are being played with a crosshair than without.

**Comment by Username-N00b-is-not-available** [comment]
That also means the players were easily able to activate the option.
@Tormentor667, what is your opinion on this?

**Comment by Tormentor667** [comment]
I agree with you @Username-N00b-is-not-available

**Comment by x3003** [comment]
Well, I managed to turn it on aswell ;) But it would be nice if it was enabled by default. Then the user doesn't have to do it.

**Comment by Tormentor667** [comment]
Also true ... well, I think activating it b default makes really sense after thinking about it for a while

**Comment by Username-N00b-is-not-available** [comment]
There are lots of options that could improve gaming experience for some users... but not for all of them at once. I love to play with `cl_capfps 1` in 35FPS, @x3003 likes to use a crosshair, some people prefer to play keyboard-only, and I guess there would be a person who plays mouse-only.
In such situations, which turn out to be a matter of the players' personal preference, I think it is better to ask oneself some questions before doing changes.
Was there a crosshair in Wolfenstein 3-D? Was it needed there, considering the one-dimensional hit detection? Is there a need for crosshair precision in a game where an enemy has only one parallelepiped hitbox?
Is the crosshair turned on in GZDoom by default? Why not? Could it be because of that the weapons are usually centered in Doom engine games? Is Blade of Agony any different?

**Comment by Tormentor667** [comment]
The only reason for a crosshair is for the free mouse-aim and the autoaim being deactivated.

**Comment by Username-N00b-is-not-available** [comment]
OK, one more question then :-)
Will the amount of people who play Blade of Agony with a controller setup that does not include a mouse be _more_ than 50% or _less_?

**Comment by Tormentor667** [comment]
Definitely less is my guess

**Comment by x3003** [comment]
>I love to play with cl_capfps 1 in 35FPS,

Only 35 ? Even on opengl I might get 50-60 sometimes ;)

>Is the crosshair turned on in GZDoom by default? 

The 'crosshair' options is enabled but doesn't do anything without the 'crosshair default' option.
But for me, I found it easier to get into the game when I can aim for something.

**Comment by Tormentor667** [comment]
Has the corrshair been activated by default now?

**Comment by Tormentor667** [comment]
The crosshair is still not activated by default, can someone take care of that? (@Talon1024 @Ozymandias81 @AFADoomer )
