### ISSUE TITLE
Change the term „Herrenrasse“ at skills into something less tasteless

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#564]
Topic says it all.

**Comment by Username-N00b-is-not-available** [comment]
Did it offend some players?
Nazi ideology is constituted by lots of tasteless and slimy things, and reading some historical accounts of how these doctrines were implemented sends _shivers_ down one's spine; but if we remove such details from the game one by one (what we have already done on multiple occasions, e. g. with some tortured sprites), what will remain of the enemy in the end? Does Blade of Agony really need to become similar to modern FPS in this way, with the opposing side being just a generic villain, distinguished only by its flags?
Oh, the swastikas can also offend people..?
![image](https://user-images.githubusercontent.com/59409713/116823467-51708880-ab8d-11eb-8d8f-9e78418569b1.png)
***
If it was the final decision, we might as well change all other skill names (to not coincide with ww-nazis anymore).

**Comment by Tormentor667** [comment]
Was it named Herrenrasse in ww-nazis as well?

**Comment by Username-N00b-is-not-available** [comment]
No (it is `Ubermensch` without an umlaut), but in BoA it was Herrenrasse from the start: https://github.com/Realm667/WolfenDoom/blob/cd44ab878f814c5d61f40c348124a38c57a83132/mapinfo.txt. That's not that much of a difference, honestly, as it is well-known that the latter concept heavily relied on the former.

**Comment by Tormentor667** [comment]
Thats a good point indeed. The question came at the doomworld forums abs I simply think of the term is too Offensive, we can change that

**Comment by Username-N00b-is-not-available** [comment]
Ah, found the source of this issue.
My opinion on that discussion is that some people in the community just _have_ to instigate and then reinforce drama from any occasion, be it a depiction of Nazi practices in a mod which is entirely about fighting Nazi Germany, or something else. And it is not the first time something like this happens on that discussion platform, I recall quite a lot even within my quite short time with the Doom community.
Maybe they are entertained by how easily and baselessly they can force their opinion on us and other modders as the only True and Moral one? Honestly I wish I could understand the psychology behind this.
***
My opinion is more in line with DavidN's post:

> I hate it when people use it in a games context, but I can just about convince myself it’s OK here. Let the nazis declare themselves the master race, then blow them to bits anyway :)

**Comment by x3003** [comment]
Well, ubermensch as in superman (as found in mapinfo.txt) should be correct.
But the nazi's used Herrenrasse/Herrenvolk/Herrenmenschen as well.

**Comment by Tormentor667** [comment]
Good point made @Username-N00b-is-not-available - what does everyne else think?

**Comment by Ozymandias81** [comment]
I would have kept Herrenrasse and never replied to the post, I am in my 40s and I am getting tired of these people rasing drama for everything... Do they remember what is life, have fun, enjoy a videogame, think free and not squared? No.

**Comment by 0Wereknight** [comment]
If I may I'd like to put my few cents here since doomworld crowd is... less negotiable that some folks like me would like to them to be.

That's just ridiculous. Through all time since mod was in developement this thing was there from the start. There's no implying that's something wrong at all, as such name for a game difficulty describes what we are about to do with nazis. Master them, in terms of slaughtering them and their morbid experiments, be strong and willingful to put an end for the Great Evil of that time period.

Unironically there's always someone who would whine\complain about such little details, not understanding how retarded\deranged it might to look from other people perspective, yet I noticed it's not even Doomworld's problem, but whole "woke" culture idea that took minds of people and messing them to irrevertable brain and mentality damage.

Just don't listen these complaints and keep things as is. Getting acknowledged of bugs and glitches in your game is one, and important thing, while this shit people trying to bring just for the sake of ill drama is unnecesarry and, honestly, not worth of listening and acting for pleasing them. Once you goes on compromise they will demand even more, until your initial idea will not fade in non-existence.

Cheers.

**Comment by MasterO2** [comment]
@Tormentor667 https://www.doomworld.com/forum/topic/71736-wolfenstein-blade-of-agony-release-v30/?page=11&tab=comments#comment-2305305 could be a good idea regarding changing the word Herrenrasse.

**Comment by Tormentor667** [comment]
> @Tormentor667 https://www.doomworld.com/forum/topic/71736-wolfenstein-blade-of-agony-release-v30/?page=11&tab=comments#comment-2305305 could be a good idea regarding changing the word Herrenrasse.

This is a very good suggestion indeed!
