### ISSUE TITLE
C2M2: Weird stuttering after the drone bots break free

### ISSUE THREAD

**Issue by pagb666** [Realm667/WolfenDoom#574]
I've just played through C2M2 twice, and I've experienced some stuttering after the drone bots break free from their cells at the cell block. The stuttering keeps going for like a minute and then stops. I don't really know if it's related to that specific area and goes away when you move on or... some scripting weirdness going on on the background?

**Comment by xSonicB00Mx** [comment]
I have noticed the same exact thing. The framerate jumps between something like 56 and 58 fps constantly. The same thing happens when you uncap your framerate and encounter the first enemies in the map (the sewer with the sleeping guard before the room). There it jumps between 76 and 78 fps. I can provide a screenshot with the framerate graph later.

**Comment by Ozymandias81** [comment]
A video would be better.

**Comment by pagb666** [comment]
https://www.youtube.com/watch?v=H81i1Fqgbe4
Best noticed when I'm running or turning the camera. Replayed the level this very morning again, same stutter.

**Comment by Ozymandias81** [comment]
Looks something related to actors logic hauling thinkers, I'll check if I can do something

**Comment by AFADoomer** [comment]
Are the drones the problem, or is it the sheer number and range of spinning lights?  More likely the latter.

**Comment by Ozymandias81** [comment]
The zone had normal minor slowdowns, to me didn't happen frequent microstutters mentioned, but thinkers where jumping from 0.20 to 1 when drones got free on script 28, and specially when they were trying to aim me... but nothing dramatic tbh, indeed I think lasers may be the reason for the mentioned issue. For a moment I thought it was related also to amount of lights on that zone, 9 alertpointlights, reducing them to 3 with just higher radius improves only a bit the chances to reduce those apparently microstutters. Later will test again performance with recent changes

**Comment by Tormentor667** [comment]
Why has this been closed? Is it fixed?

**Comment by Ozymandias81** [comment]
Microstutters aren't something easy to track, specially because some experience them some not, and in this specific case AFA did something regarding lasers impacts in terms of performance. So since the issue is very vague, I decided to close it also because on that specifical zone I don't get crazy slowdowns or such, just very very very minor unnoticeable fps drops, and I am the one with the lowest rig specs.

**Comment by Tormentor667** [comment]
Very good, thanks for elaborating.
