### ISSUE TITLE
Nemesis stun animation

### ISSUE THREAD

**Issue by DoomJedi** [Realm667/WolfenDoom#592]
Nemesis should loop M and N frames (intended 2 frame stun animation) as long as he is stun. Currently he doesn't.

...also SEETO0 frame not properly recolored.

**Comment by Ozymandias81** [comment]
SEETO0 has been recolored a couple of commits ago, and regarding Nemesis, since we moved to zscript, idk how to make it loop without using tons of MN calls but also without breaking the intended actor behavior with the custom function. But I added a [note](https://github.com/Realm667/WolfenDoom/commit/8df22011f2adbb907bc5245d2859367a4a42d15b#diff-9ead5649b4a52f01cdc900917d9a0361a9c9795a774ec61989e9d21ff6407081R300) there a couple of days ago.

**Comment by Talon1024** [comment]
Like this?

https://user-images.githubusercontent.com/6550500/117549221-26f85280-b007-11eb-91dc-f7765cec66de.mp4

**Comment by DoomJedi** [comment]
> Like this?
> 
>  NemesisKneel.mp4

Yes,  thanks :)

**Comment by Tormentor667** [comment]
I liked it more before. Without the animation you weren’t sure if he is dead or not. Now the surprise factor is gone.

**Comment by DoomJedi** [comment]
You're the boss, Torm, do as you prefer. It's not that critical to me. 
I thought moving Nemesis is more spooky than still one, that's how the animation was envisioned.
Do as you like, it's your vision.

**Comment by Talon1024** [comment]
Well, you can revert f2f6a0db25454ceec783d65c6149120d17f5d2de to restore the non-animated version.

**Comment by Ozymandias81** [comment]
So we gonna keep it with a cool animation or just as it was before?

**Comment by Tormentor667** [comment]
As it was before please
