### ISSUE TITLE
C3M1-A - The guard of the red key door is unkillable.

### ISSUE THREAD

**Issue by Gadgetdan** [Realm667/WolfenDoom#641]
I started to play the 3rd episode and I think I was able to skip a couple of sections on the game since before I picked up the radio to be given instructions for my mission I was able to find the red key on the grave yard and just run for it towards the red door with the guard, I was able to kill several guards inside and I was even able to fight one of the bosses however the same guard from the entrance look unkillable. After I found the shovel I went back and use GodMode to stand on front of the guard and hit him with the shovel 40 times, his health never went down. To continue the game I used the code for instant kill the guard, then I proceeded to play the game without cheats.

**Comment by Ozymandias81** [comment]
That guard is intentionally unkillable, we don't support cheating and if you enter the zone and try to kill him right down the door instead to go upstairs the guarding tower (where you open the gate with the shovel), only when you are there you can kill him, otherwise being able to not kill from the tower would mean game breaking action, and also you are supposed to sneak in disguise. The guard becomes killable only once you collect the sniper rifle on the said tower and kill him from there, using the scope from the broken windowsill.

**Comment by Gadgetdan** [comment]
Oh ok, I guess I kinda broke down the game by mistake by doing things in
different order, I don't know if there is a way to prevent that from
happening accidentally.

Gadget Dan .......

**Comment by Tormentor667** [comment]
Thats the point - cheating may break the game :)

**Comment by Gadgetdan** [comment]
Actually when I said I broke the game by mistake was because I didn't
cheat, I was playing the game normally and by mistake I followed a path I
wasn't supposed to.

Gadget Dan .......


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
