### ISSUE TITLE
C1M5: Allied troops can be killed by Nebelwerfer fire from the player.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#684]
In Operation Paris, the cavalry that arrives near the end of the mission can be harmed and/or killed by the player's Nebelwerfer projectiles. Perhaps include some pathfinding logic that has them steer clear of this weapon's line of fire?

**Comment by AFADoomer** [comment]
They kind of do already...  the same code that makes Nazis run away from flames and grenades.  The projectiles here just move too fast for them.

**Comment by Ozymandias81** [comment]
Well allied soldiers are already very resistant to bullets, I think it is better to keep things as they are since they work already fine imho. One just have to be careful to not hit them, but this is needed anyway otherwise we would see allied soldiers flying in air everywhere and it would are worse things then. Just use the nebelwerfer wisely.
