### ISSUE TITLE
incorrect icon for guards when using a knife

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#687]
With todays git, in c2m1, when having the knife and go up the guards in the towers, there's no knife icon shown, but instead an icon of the sniperrifle.

![Screenshot_Doom_20210523_164936](https://user-images.githubusercontent.com/77861029/119270967-a1c48e80-bbff-11eb-9b57-627e6a831ea4.png)

**Comment by Shockwave508** [comment]
Seems like the "sniper alert" crosshair is overriding the backstab icon somehow.

**Comment by Username-N00b-is-not-available** [comment]
Only one crosshair could be shown at a time, and the backstab icon is also shown as a crosshair IIRC.

**Comment by x3003** [comment]
Notice that this crosshair isn't only shown from upclose, were the knife icon should be. But also at a larger range, were the knife icon never shows.

![Screenshot_Doom_20210523_164923](https://user-images.githubusercontent.com/77861029/119387274-026bce00-bcc9-11eb-92d2-69311e4c9032.png)

**Comment by Ozymandias81** [comment]
Those icons gets applied over actor properties when mapping, and they are there since one may want to circumvent those guards and not kill them, but then approach later when being on the courtyard, and there spotlights makes difficult to aim at them. It is like with arctic rifleguards on snowy maps, those indicators are there for this reason, and as N00b said only one icon can be shown per actor.

**Comment by x3003** [comment]
>they are there since one may want to circumvent those guards and not kill them,

Why shouldn't you wanna kill them ? If you're already up in the tower, you have to. Else they might spot you when leaving.
