### ISSUE TITLE
Lt. Laz Rojas' Armory Shop: Display amount of gold in this menu.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#713]
The amount of gold the player has on hand needs to be displayed somehow in Lt. Laz Rojas' dialogue menu, regarding the Armory. Currently, the player repeatedly has to exit, then reenter dialogue to closely monitor his funds.

**Comment by AFADoomer** [comment]
Does anyone know if there is a reason that the shop dialogue has the costs included in the item strings instead of using the built-in cost printing?  The easiest way to show the player's gold amount is to use the already-built-in handling to do so, but we're currently (unintentionally?) not allowing that to work.

**Comment by AFADoomer** [comment]
This should be good to go after 0d68d8dff574bc4b7296f503710d938a0dff4f49.

**Comment by Shockwave508** [comment]
It introduced a new glitch when talking to Prof. Gutenberg. The dialogue option to give him an Eisenmann File/Mayan Artifact/etc. has a "store price" of $1. Thankfully nothing gets deducted if you select that option.
![Screenshot_2021-06-03-23-33-32-063_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/120746096-28ad1d00-c4c4-11eb-887b-a29c62335698.jpg)

**Comment by AFADoomer** [comment]
That's what I get for doing a find-and-replace...

**Comment by AFADoomer** [comment]
OK, should be fixed in caa63c41be29656d6c3fb1e1a605394411aef048.
