### ISSUE TITLE
INTERMAP - HQ

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#728]
INTERMAP -HQ ...

Notice the different floors at sectors 1141 to 433 and when going from sectors 1147 to 1148. Also check ceilings when crossing line 4692.

**Comment by Tormentor667** [comment]
I fixed the broken floor alignment, but what do you mean with the floor/ceiling differences? The flats are correctly aligned, I can only imagine you notice something with the ambient occlusion. Can you record a video?

**Comment by hawkwind3** [comment]
Here is a screenshot of the ceiling of sector 1147.

________________________________

**Comment by Tormentor667** [comment]
Unfortunately not attached. Can you directly post it in the issue instead of replying via mail?

**Comment by Ozymandias81** [comment]
Differences listed here, from to non-fixed to actually fixed by me :)

![Screenshot_Doom_20210602_130549](https://user-images.githubusercontent.com/11136108/120472037-bba36580-c3a5-11eb-8359-15cce143d0d3.png)
![Screenshot_Doom_20210602_130552](https://user-images.githubusercontent.com/11136108/120472049-be05bf80-c3a5-11eb-9314-60089099ba2d.png)
![Screenshot_Doom_20210602_131125](https://user-images.githubusercontent.com/11136108/120472057-bfcf8300-c3a5-11eb-8f30-f105fe281ca6.png)
![Screenshot_Doom_20210602_131131](https://user-images.githubusercontent.com/11136108/120472063-c0681980-c3a5-11eb-81b1-c4f9ac181a37.png)
