### ISSUE TITLE
[C3M5_B] Issues with scrolling luggage

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#784]
Near sector 2250 there is what seems to be a luggage conveyor, but some sectors do not work, and others scroll in the wrong direction.

**Comment by Ozymandias81** [comment]
Again, which version of GZDoom are you playing with?

**Comment by hawkwind3** [comment]
Using the boa.exe that came with the distro.

**Comment by Ozymandias81** [comment]
Looks like it requires scripting to work correctly, as seen on C2M5_A for example and specially C1M2: I had to use SCROLL_AND_CARRY, still fixing bits to move properly everything... Spent an humongous amout of time XD
Also I think we must choose a different tx, since scaling messes up visuals here.
![image](https://user-images.githubusercontent.com/11136108/122458859-8eaf9f00-cfb0-11eb-9ffb-a6fb3ead8789.png)

**Comment by Username-N00b-is-not-available** [comment]
This is way better, thank you very much!
