### ISSUE TITLE
[C3M1] Jewish references

### ISSUE THREAD

**Issue by DoomJedi** [Realm667/WolfenDoom#797]
*EDITED BY TORM*

- [x] Change escape plan to use german instead of hebrew
- [x] Remove "Holocaust Survivor" medal on texture
- [x] Replace "Sonder" easteregg screenshot (Why? - Talon1024)

> I Agree with Talon1024 - I don't see why the mission name or Sonder easter egg need to be changed. Does the mission name have some real-world meaning that I don't understand?  And I didn't even know the Sonder egg was such, except by the file name. - AFA

**Comment by Tormentor667** [comment]
I am not going to remove this because of denying anything. I simply asked here as well „Is it needed to tell the story?“ As already mentioned: Things are handled different kn Germany and I simply want to remove any problematic content now that we have such a negative attention going on.

**Comment by DoomJedi** [comment]
> 
> 
> I am not going to remove this because of denying anything. I simply asked here as well „Is it needed to tell the story?“ As already mentioned: Things are handled different kn Germany and I simply want to remove any problematic content now that we have such a negative attention going on.

I didn't say you deny Holocaust or what to deny it.
I say changes - are a big gift to holocaust denyers and jew-haters and will please them much.

**Comment by Ozymandias81** [comment]
Should we use a different name for zyklon, maybe replace it with fictional gazklon?

**Comment by madame-rachelle** [comment]
I am secular so I cannot speak for what any member of any religion may or may not find offensive, and thus I do not think I can offer very much in the way of valuable insight on this topic.

I am sorry to water this down to a generic statement but given my COMPLETE lack of knowledge on this topic, that is all I can do.

The only thing I really can say is this: I am against white-washing history. If some things must be shown in order to keep historical integrity/accuracy, no matter how ugly they may be, I would be in favor of keeping that. Hitler and the Nazis were unequivocally evil and I personally would prefer that the mod drills that point home for players, and I hope I have shown thus far to have been reasonably consistent about that since this whole issue started.

I am not trying to "make X religion or Y religion" happy, or any terrorist groups frequently associated with them.

This issue is just simply not my fight. I do not belong on this thread because I cannot speak for anyone concerned on this topic.

**Comment by AFADoomer** [comment]
If we want to rename the gas, maybe Hurrikan or Taifun instead of Zyklon?  Thinly veiled, but at least not the same name.

**Comment by DoomJedi** [comment]
Dont we have zyklon signs too? Textures?

**Comment by x3003** [comment]
>Should we use a different name for zyklon, maybe replace it with fictional gazklon?

Maybe make it vitamin c instead ?!

**Comment by Dynamo128** [comment]
> Maybe make it vitamin c instead ?!

Really? You think this is something worth joking about in these terms?

**Comment by x3003** [comment]
>Really? You think this is something worth joking about in these terms?

No, but this is a fictional game, based on reality.
There are already too many ppl in the world trying to make everything politically correct. I know enough of the war and seen too many images of ppl getting killed by nazis and others to not joke about it.
But having to change a lot in a 'simple' game because of a few ppl are insulted is ridiculous.

**Comment by Ozymandias81** [comment]
Okay then no changes to Zyklon, I surely like it this way.

**Comment by DoomJedi** [comment]
Good call.

**Comment by Tormentor667** [comment]
The point with Zyklon C is, that it very obviously refers to Zyklon B - yes. We could rename it as it has been stated various times, that it is a more evil version of Zyklon B, so people would get it. But how much sense does it make to rename it? I really would like to know everyone's opinion about it.

**Comment by AFADoomer** [comment]
I say leave it as-is (Zyklon C).

**Comment by Ozymandias81** [comment]
Again if it was for me, I would have kept everything as is, mine was just a suggestion. And better keep it as is, since we have several textures with the name too.

**Comment by Username-N00b-is-not-available** [comment]
Has the developer team exhausted the subject of discussion here?

**Comment by DoomJedi** [comment]
Changing gas name? Really?
...no words can describe how it looks to me.

Is it german law, just our panic or what?

**Comment by Tormentor667** [comment]
We keep Zyklon-C

**Comment by Tormentor667** [comment]
Now that everything has been discussed and taken care of, we can safely close this. Thanks here as well!
