### ISSUE TITLE
HUD Pickup Messages (Typo): Petrol Canisters (Flamer Ammo) claims to give +25 Fuel, gives +12 instead.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#802]
When picking up petrol canisters from slain Flammenwerfer-toting enemies, the pickup message says you got 25 Fuel, when in fact you only get 12.

**Comment by Username-N00b-is-not-available** [comment]
This is sadly not a typo. Remember how Doom's shotgun guys drop shotguns with 4 shells instead of 8 for map-placed shotguns... It should also happen with all other ammo types in BoA.
Maybe messages from #740 should have not been added right into the CSV after all, special ZScript handling could deal with this problem, but the code would become a whole lot more difficult and messy, considering that the virtual HandlePickup() method would need to be overridden in EACH of the base subclasses for our inventory items. It would overcomplicate things too much.
On the other hand, I have already suggested once that we make the 'detailed' pickup messages an optional addon...

**Comment by Username-N00b-is-not-available** [comment]
Ah, yes, there's also that method. Totally forgot it. Fine then, thank you! I'll remove the lines from the CSV then.

**Comment by AFADoomer** [comment]
We still need the descriptor words (Armor, Health, Shells, Rounds, etc.) as entries in each language, though. Not sure if declensions will become an issue.

**Comment by Username-N00b-is-not-available** [comment]
They definitely could become a problem, but we can avoid them with something like 'Патроны x5' ('Rounds x5') where the first word is always in plural.

**Comment by AFADoomer** [comment]
Can you create entries with "%a" as a placeholder in the correct spot (i.e., "Патроны x%a"), based on thr current text entries?  Then I can use code to replace the placeholder with the correct amount for each drop and append it in parenthesis to the end of the regular pickup string.

**Comment by Username-N00b-is-not-available** [comment]
Unrelated: BTW, @AFADoomer, does your last phrase in https://github.com/Realm667/WolfenDoom/commit/0bcd0e6865c198395787c56fc7f18725843f3711 mean that you have already written the messages, or only that the code for new achievements has been present on your machine for two days?

**Comment by Username-N00b-is-not-available** [comment]
@AFADoomer I have collected the text entries in English, German, Russian and Czech (@MuadDib90, could you please check it around line 530? :-) ) into identifiers ITTYPExx (xx from 01 to 14). The %a placeholder is not needed, you can just append the same string like English "(Ammo +64)" in all languages, it will look fine.
I will remove 200 instances of these scattered across the CSV tomorrow, it's really late in my country now...

**Comment by AFADoomer** [comment]
That commit had been sitting on my computer for 2 days. Lines aren't written yet.

**Comment by AFADoomer** [comment]
@Username-N00b-is-not-available - Better to leave the lines as-is and replace the amounts with %a so that I can do a simple replacement with the amount and don't have to do any extra tracking to figure out the right 'type' work to print.  I can't replace the pickup string at runtime like I thought I could because the variable is 'meta' tagged for some reason, so I'm going to have to touch a bunch of classes anyway, but luckily there are really not that many base classes that will need to be updated.

**Comment by AFADoomer** [comment]
This should be taken care of in 41a3e6ad493c96f28b1b8af56e5539ba8c32115a.

**Comment by Shockwave508** [comment]
Two more issues.

Stahlhelm pickup message displays +1 Armor, actually gives +5.
Nazi Medkit claims to give +10 Health, when it gives +18 over time.

**Comment by AFADoomer** [comment]
Fixed the stahlhelm.  The Nazi medkit is hard-coded to say +18 in language.csv, so I'm not sure what you are seeing there...

**Comment by MuadDib90** [comment]
@Username-N00b-is-not-available 
I checked the CSV. Thank you.

@AFADoomer he means, that Nazi medkit doesn't give you instantly all amount, but it rises to the max. over time (similary to bandages), am I right? @Shockwave508

**Comment by Username-N00b-is-not-available** [comment]
@MuadDib90 No, not about that, we are talking about the complete amount which is given by the item.
I think @Shockwave508 refers in https://github.com/Realm667/WolfenDoom/issues/802#issuecomment-859823670 to some previous version of the language file, it was indeed written 10 there in the initial implementation, then I spotted it and changed it to 18 one or two days ago.

**Comment by MuadDib90** [comment]
Ah, OK then.

**Comment by Tormentor667** [comment]
I guess this is fixed then.
