### ISSUE TITLE
Strange E-Mail gotten from "Spirit Bomb"?

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#809]
Just got this:

> That better not be due to you sharing my email or trying to fuck with me. I am deleting this email and would be thankful to be cut from the credits. Thank you. I find it odd I get a mac log on right around 10 pm yesterday after I left the project, if you have given my personal private info out to someone I will genuinely have a serious problem with you.

No idea if it is spam, scam or something else. Ignore?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Could it be Wolfenburger?

**Comment by Tormentor667** [comment]
I absolutely have no idea...

**Comment by Wolfenburgernator** [comment]
> I absolutely have no idea...

It was me. If you checked your messages on moddb I confirmed it wasn't you that got into my email. It was some random Russian bot on a Mac. I was concerned it was you giving my email out or it being breached due to me taking a stand due to the mod censoring. Regardless you're clear torm and I'd appreciate it if you didn't mention my my email pen name on this thread. Regardless you're name is cleared. It wasn't you. However I wish to be cut from the credits and I sent a lengthy message on moddb. However you must not check them.

**Comment by Tormentor667** [comment]
I just replied your pm over there, thanks fpr apologize and clearing up.

**Comment by Ozymandias81** [comment]
Fixing graphics and credits atm

**Comment by AFADoomer** [comment]
Should probably edit this issue to remove his email display also.

**Comment by Wolfenburgernator** [comment]
> Should probably edit this issue to remove his email display name also.

I think you can outright delete issues. Which would be better so we don't have snoopy people looking at edit histories

**Comment by Username-N00b-is-not-available** [comment]
This can only be done by @Tormentor667 as an admin: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/deleting-an-issue

**Comment by Wolfenburgernator** [comment]
> This can only be done by @Tormentor667 as an admin: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/deleting-an-issue

I'm sure he'll get around to it when he has a spare moment.

**Comment by Wolfenburgernator** [comment]
I don't know if referencing this as an issue will keep it ghosted and linked. @Ozymandias81 it might keep this thread linked even after deletion. Might have to ask you to delete that thread reference link. Hate to be an annoying prude.

**Comment by Wolfenburgernator** [comment]
@Tormentor667 I replied to your email btw.

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 Could you please delete this issue altogether?

**Comment by Tormentor667** [comment]
Which ones should I delete?

**Comment by Wolfenburgernator** [comment]
> Which ones should I delete?

Delete the issue and stop publicly posting my personal information thank you! And delete that reference Ozy made

**Comment by Wolfenburgernator** [comment]
> Which ones should I delete?

@Tormentor667 it's not hard man I asked in an email. You have to click 3 dots and click delete on this thread or "issue" as for the reference that's a simple remove as well. I'm beginning to think your screwing with me and I'll report for public posting of my pen name because it is my personal info and I never asked for you to share it.

**Comment by Wolfenburgernator** [comment]
@Username-N00b-is-not-available Hey is there any direct line you have to Tormentor667? I would like this issue deleted and I'm coming close to having an actual anxiety attack.
