### ISSUE TITLE
player.movebob is an unknown actor property

### ISSUE THREAD

**Issue by TarekSaid** [Realm667/WolfenDoom#82]
Using GzDoom g2.2.0 x64 and the lastest WolfenDoom build (as of 03/11/2016), I get the following error:

```
Execution could not continue.

Script error, "wolf_boa.pk3:actors/misc/player.txt" line 35:
"player.movebob" is an unknown actor property
```

After removing the aforementioned line in player.txt I am able to run the game.

**Comment by Gaerzi** [comment]
Yes it's a new property that requires a development build, so BOA will not work with 2.2.0 anymore.

**Comment by Ozymandias81** [comment]
BTW it's player.viewbob afaik, and yes [you need at least r252](http://devbuilds.drdteam.org/gzdoom/gzdoom-g2.3pre-252-gf0ee3e3.7z) in order to play BoA now (but also you'll get some more issues, for example if you use Kick weapon GZDoom will hang then crash... [which is related to this I guess](http://forum.drdteam.org/viewtopic.php?f=24&t=7290))

**Comment by TarekSaid** [comment]
oh ok, thanks!
