### ISSUE TITLE
C2M0_B scrolling doortak fix

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#830]
C2M0_B scrolling doortraks

Attached is the doortak scrolling fix for map c2m0_b. I was told that the scrolling was intentional, but this normally is not a good look.
[C2M0_B.zip](https://github.com/Realm667/WolfenDoom/files/6652400/C2M0_B.zip)
This is an update to the latest in the code uploaded 8hrs ago.

**Comment by Ozymandias81** [comment]
Which doors and in which place please?

**Comment by Username-N00b-is-not-available** [comment]
@Ozymandias81 Most probably a) in https://github.com/Realm667/WolfenDoom/issues/817#issue-919706136.

**Comment by hawkwind3** [comment]
>Which doors and in which place please?

Using the uploaded version, doortraks for sectors 278, 294, 352, 356, 765, 621,618, 1011, 1025, 1028, 2571, 2568, 2556, 2559,
6977, 6974, 6962 and 6969. Note new sectors attached to these.

**Comment by Tormentor667** [comment]
What did you change anyway? I can reproduce this then.

**Comment by hawkwind3** [comment]
>What did you change anyway?

see above.

**Comment by Tormentor667** [comment]
I just mean what did you alter on the lines?

**Comment by hawkwind3** [comment]
Basically, before the update, the doortraks would scroll, which is not a good look, the update fixes those. Best explained by downloading my fix, and checking the additional sectors ( and lines ) attached to the sectors mentioned in this thread. I cannot explain it better, other than a larger post.

**Comment by Username-N00b-is-not-available** [comment]
On split doors such as this one
![image](https://user-images.githubusercontent.com/59409713/122753760-615a3e00-d29b-11eb-9156-23037a01d65e.png)
the door tracks always scroll with either the upper or lower part, no matter if you use Lower Unpegged flag on them. @hawkwind3 added small sectors around them, so that the linedefs in question become two-sided and do not display the texture anymore, but new lines that are attached to new sectors do not scroll:
![image](https://user-images.githubusercontent.com/59409713/122754126-e9404800-d29b-11eb-9ba7-2bd103949cf8.png)
I am reimplementing these changes now.

**Comment by Tormentor667** [comment]
Understood now, thanks for the clever fix.
