### ISSUE TITLE
Remove useless item

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#845]
Why not remove the mine from the shop ? This item is pretty useless, as most (all ?) players never gonna buy or even use it. The game is just too fast for it. And there are no missions who require buying it. So why keep it in the shop ?

**Comment by Username-N00b-is-not-available** [comment]
We now have an achievement connected with using it :-D
I agree that the mines are useless as of now both in single player and multiplayer, I remember writing such a suggestion myself (to remove mines altogether). Enemies avoid them (except patrolling sneakable ones in C2M6_B, dogs, scientists/mechanics and bosses), their range and damage are too low, on the level of a grenade or possibly even lower, which is a joke since an M24 contains around 70g of explosives, but all types of Nazi German anti-personnel mines contained at least 140~200g (not to mention that our mines are most probably based on the anti-tank [Tellermine](https://en.wikipedia.org/wiki/Tellermine_42) with 5kg of TNT).
Now I don't think we should remove the mines, but rather rebalance them, considering possible combat situations they could be useful in. Since enemies won't step on it, it would be great for blocking corridors, and the player should also have a way to detonate it easily from afar; I propose changing its health from 10 to 1, so it detonates instantly after being shot. I think we should also:
- make it bounce in air on being triggered, like the [S-mine](https://en.wikipedia.org/wiki/S-mine), 32 units should be enough (this is mostly decorative, but also sends more shrapnel right into enemies);
- significantly raise radius and damage of the explosion (double both parameters?);
- add a huge shrapnel explosion to it, larger than that of an SS Übersoldat's grenade (like C1M5 Nebelwerfer?)

**Comment by x3003** [comment]
>Since enemies won't step on it, it would be great for blocking corridors, and the player should also have a way to detonate it easily from afar;

Could be used for multiplayer, but they should then be a lot cheaper, coz no one gonna buy them if they're too expensive and lose a lot of 'cash'.

**Comment by Username-N00b-is-not-available** [comment]
If used in multiplayer (deathmatch), they would mostly be spawned as map pickups, not sold.

**Comment by AFADoomer** [comment]
Is it more useful after 32c2dbcadb9cb2687f0d4fea4f899de067f537f5?

I decreased the avoidance radius and added a small delay to the explosion so enemies will walk up on the mine and set it off, but will "notice" it then, and attempt to dodge/roll to try to escape the explosion.
