### ISSUE TITLE
Dogs don't move

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#848]
In c3m0_b these 2 dogs don't move at all. Maybe they are statues ?

![Screenshot_Doom_20210617_235829](https://user-images.githubusercontent.com/77861029/122479080-cfb4ad00-cfca-11eb-913d-3895dee580bc.png)

**Comment by DoomJedi** [comment]
Guys remember that was my report before the release

**Comment by Username-N00b-is-not-available** [comment]
Here is what happens in editor. Lines:
![image](https://user-images.githubusercontent.com/59409713/122521061-0d422600-d01d-11eb-9388-352afca13b93.png)
Things (light blue = mines, mostly):
![image](https://user-images.githubusercontent.com/59409713/122521203-3662b680-d01d-11eb-9347-a66139662aae.png)
A minefield is not reliable in blocking players from entering an area — especially if the player is willing to cheat (this is also seen near C3M3_A river). We could add player-blocking lines around the mines, but an easier solution would be to move that linedef and rotate it so it spans almost all of the sector 1219 vertically.

**Comment by Ozymandias81** [comment]
That never happened to me, seems to be a similar issue encountered with a couple of AlliedSoldiers on c3m2... maybe just activate dogs once we enter that big zone? I will put them 4mp higher too, just in case since that was the issue with soldiers on c3m2 (they got stuck if placed at 0-3 mp) - Those are the ones near the first rendez-vous, at the allied base
