### ISSUE TITLE
C2M5_B mor issues

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#882]
C2M5_B ...

a) T2989, T3039, 3021 and T2990 partly render into the ceiling slope.
b) tex at line 16180 etc. need textures on their back sidedefs.
c) Sides of doors at these coorinates are wrong - x 5579 y12985, x5188 12812, x 4409 y 12460, x 4130 y 12755, x 3658 y 13014.
d) Does the switch at x 4123 y 12836 do anything ?
e) When at sector 78, on the 3d foor, I was pushed by the fan into sector 3071, but did not die, but regenerated health.

**Comment by Username-N00b-is-not-available** [comment]
a) Now that is a nitpick among nitpicks... Moved each one 8 units outside the slope.
b) These ones? They already have textures:
![image](https://user-images.githubusercontent.com/59409713/122995253-0c5d1b80-d3b2-11eb-8694-8b43d628f5b4.png)
c) I reported some of these recently, and most were already fixed. Fixed the last one.
d) Not anymore, thank you! Removed it.
e) Can not reproduce this at all. Could it be because of a spare Totale Macht in your inventory..?

**Comment by hawkwind3** [comment]
b) Sorry. What I meant was those lines can be jumped/clipped into AND, again sorry, lines 8371, 8251 etc. ( coords 5184, 4064 ) need mid textures on their back sidedefs.

**Comment by Username-N00b-is-not-available** [comment]
There's absolutely nothing to be sorry for, it is our interest to know about bugs and fix ones that we can — you are helping us greatly! Thank you very much for it.
b) Made these walkable + projectile shoot-through.
8371/8251: added, also added to the copy of this pillar on the northern side of the room.
Will commit soon.
