### ISSUE TITLE
stamina and kick

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#913]
If you kick, the stamina meter goes down. So after a few kicks, you can't run anymore because you're 'out of breath'.
Is this by design ?

![Screenshot_Doom_20210701_231211](https://user-images.githubusercontent.com/77861029/124294220-b9285d00-db57-11eb-91ab-5e0be782fc75.png)

**Comment by Username-N00b-is-not-available** [comment]
Yes, this is definitely intended.
I wonder if jumps could also be coded to use stamina... and if they should.

**Comment by MuadDib90** [comment]
> 
> 
> Yes, this is definitely intended.
> I wonder if jumps could also be coded to use stamina... and if they should.

As @Username-N00b-is-not-available says. 
I don't know how much stamina the jump should use, but I can imagine the situation as: running, running to overcome some obstacle, aaaand at the end you won't jump, because you won't have enough stamina left... (but this is maybe the worst scenario)

I understand you, but considering - in my mind - this is a descendant of Doom legacy in fast-paced gameplay, I wouldn't recommend it. On the other hand, I wouldn't be also mad, if coded in.

**Comment by Tormentor667** [comment]
This is by design and supposed to be kept as is.
