### ISSUE TITLE
[3.2] Speaking during movie

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#915]
During the movie, you can also use the use-key to speak w/ Ascher. So maybe turn him off while the movie runs.

![Screenshot_Doom_20210702_165403](https://user-images.githubusercontent.com/77861029/124295125-c3972680-db58-11eb-9d9f-114f116920bb.png)

**Comment by Tormentor667** [comment]
This could be solved by removing the conversation id while the briefing is running and adding it back as soon as it is over. Should be the same id through the whole game.

**Comment by Tormentor667** [comment]
I checked the scripts now and the problem is that Asher's conversation id changes several times through the whole game. We can not deactivate it and reactivate the conversaion id in general as we do not know which conversation is active. The solution that applies to the General doesn't work for Asher.

I tried a different approach now by using the "INCOMBAT" flag and it works.
