### ISSUE TITLE
[3.2] Different death message if single player or multiplayer (playername < - > BJ)

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#916]
When you die, you don't die as BJ, but as the name set in gzdoom. In the release version it still worked.

![Screenshot_Doom_20210702_223929](https://user-images.githubusercontent.com/77861029/124326487-c0b32a80-db86-11eb-8a29-7251d0d680cb.png)

![Screenshot_Doom_20210702_173717](https://user-images.githubusercontent.com/77861029/124326029-0a4f4580-db86-11eb-9943-0207662b449d.png)

This is from the release version.

![Screenshot_BoA_20210702_224151](https://user-images.githubusercontent.com/77861029/124326604-f821d700-db86-11eb-967f-06c0a116127a.png)

**Comment by Username-N00b-is-not-available** [comment]
```B.J. Blazkowicz``` was just set as the default name for BoA players instead of ```Player```, and you can change it from the settings menu in all recent versions, including 3.0 release.
Given that we have plans for adding coop support in further updates, hardcoding Blazkowicz into the obituaries would be unwise (how would the players in a 4-player session know who died, then?)

**Comment by x3003** [comment]
>hardcoding Blazkowicz into the obituaries would be unwise

Well, in a 1 player game it could be B.J. Blazkowicz and in a coop game it should be Player.
Something like
if player > 1
 name  = 'Player'
else
 name = B.J. Blazkowicz

**Comment by Tormentor667** [comment]
> Well, in a 1 player game it could be B.J. Blazkowicz and in a coop game it should be Player.
> Something like
> if player > 1
> name = 'Player'
> else
> name = B.J. Blazkowicz

That would be nice to have though. Is something like this doable? Could be interesting for 3.2

**Comment by AFADoomer** [comment]
To do it properly, we'd have to override the GetObituary function in every damage-causing actor class (not a big deal, since most inherit from Base class), but there's no good way to handle environmental deaths (drowning, lava, etc).

The easy but naive solution is to replace the player name with "B.J. Blazkowicz" in every death message at runtime when not in multiplayer, but that runs the risk of replacing unwanted portions of the string (i.e., if someone named themself 'Nazi' or 'kill' or 'was'.)

**Comment by Tormentor667** [comment]
Good point. In this case I’d suggest making the default player name not “Player” but “B. J. Blazkowicz” and the player can customize it themselves.

**Comment by AFADoomer** [comment]
Already done a while ago...  The name only shows up as "Player" if someone started playing with their current .ini before DEFCVARS was updated, or if they are playing with BoA as a PWAD (or if they change it themselves) afterward.
