### ISSUE TITLE
[C1M1] Floating rocks after exploding wall

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#922]
In c1m1, with the latest git version and gzdoom pre 62/67, there are 2 rocks floating.

![Screenshot_Doom_20210704_155041](https://user-images.githubusercontent.com/77861029/124388550-b78ba000-dce3-11eb-9714-93668030a179.png)

![Screenshot_Doom_20210704_164231](https://user-images.githubusercontent.com/77861029/124389361-fff88d00-dce6-11eb-93cf-d4eb6b439aa3.png)

**Comment by Tormentor667** [comment]
Please use the latest stable version of GZDoom (4.6) for testing, no dev versions please.

**Comment by MuadDib90** [comment]
Isn't there some mistake? @Ozymandias81 always say to use latest dev built...

**Comment by x3003** [comment]
Strange, can't reproduce it anymore. Not w/ 4.6 nor the dev version.
Personally I test to see if it gets a speed improvement or maybe breaks the game or something else. Can report back to gzdoom git then.

**Comment by Ozymandias81** [comment]
Stable or latest, you always need to verify if these issues happens with older builds of gzdoom and then compare with new ones. It is an issue that sometimes happen when GZDoom gets updated during new builds, but if it works in fine in a stable build, then you need to wait for when the behavor will be "fixed" on newer version. Otherwise report it on GZDoom github repository issues.

**Comment by x3003** [comment]
With the 3.1 release version, I still got it (ones) on the same rocks. So it can still happen.

![Screenshot_BoA_20210710_135042](https://user-images.githubusercontent.com/77861029/125162660-7d117f80-e189-11eb-8b22-a70102243843.png)

**Comment by Talon1024** [comment]
I think this is one of these issues that happens at random, and I don't think there's much that we can do about it, due to how actor hitboxes in the Doom engine work.
