### ISSUE TITLE
[3.2] Issue with volcano skybox at C2M6_C

### ISSUE THREAD

**Issue by Ozymandias81** [Realm667/WolfenDoom#948]
As the below image says, someone on Discord boa channel got again the infamous issue on that zone.
![image](https://user-images.githubusercontent.com/11136108/125335363-c231df00-e34c-11eb-81c6-522aa791b064.png)

**Comment by AFADoomer** [comment]
Make sure they are actually running 3.1 and not 3.0...

**Comment by Ozymandias81** [comment]
Let's see what the dude will say.

**Comment by Ozymandias81** [comment]
He says it's on 3.1
![image](https://user-images.githubusercontent.com/11136108/125352143-31193300-e361-11eb-851d-ad3c0a874d99.png)

**Comment by Tormentor667** [comment]
Looks good for me...
![grafik](https://user-images.githubusercontent.com/10298439/125508210-8042f7ec-096c-4965-a1ab-6e1599f67b06.png)

...except for the ending:
![grafik](https://user-images.githubusercontent.com/10298439/125508384-ae41935f-f8bc-4480-8660-e6e001a5643a.png)

I think this happens because of the portal/line teleporter as soon as you enter the lower levels of the Hades' Facility.

**Comment by Chaos442** [comment]
I get the reverse ending is fine beginning is 
Glitched on 3.1. it’s the opposite when I played 3.0

**Comment by Chaos442** [comment]
Loving the performance tho the game ran so smooth even on the zombie bonus level with 3.1

**Comment by AFADoomer** [comment]
This should be resolved now.

**Comment by Tormentor667** [comment]
It works, thanks for fixing!
