### ISSUE TITLE
[3.2] Armor class is not saved upon entering and leaving a Keen level.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#978]
When entering a Keen level through INTERMAP, the player's current armor class is not saved, leaving the player with null, zero-protection "armor" upon returning to INTERMAP. For example, I had a partially-depleted Flak Jacket, and the armor graphic changed to the Heavy Combat Vest upon returning from the Shadowlands.

**Comment by Tormentor667** [comment]
Not again 🤦🏻‍♂️

**Comment by Tormentor667** [comment]
@Shockwave508 can you check if this problem still happens?

**Comment by Username-N00b-is-not-available** [comment]
@Tormentor667 I confirm this, at least for SM01. By the way the princess message became even more mysterious than before:
![image](https://user-images.githubusercontent.com/59409713/233839753-2544f54a-201f-451a-8d16-a75b8bd5bee4.png)
All other messages on SM01 seem to be fine.

**Comment by Talon1024** [comment]
In my experience, the armor class is restored properly after completing a Keen level without dying, but not if the player dies and returns to INTERMAP.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 Currently even if I do not die and just ```fly``` directly to the end of the level, the armor class is not saved for me.

**Comment by Talon1024** [comment]
I'm working on a fix for this in the [fixAttempt/holdArmor](https://github.com/Realm667/WolfenDoom/tree/fixAttempt/holdArmor) branch. Hopefully, that will solve this issue for good, since the player (for some reason) ALWAYS has both a BasicArmor and a HexenArmor.

**Comment by Talon1024** [comment]
I just merged the [fixAttempt/holdArmor](https://github.com/Realm667/WolfenDoom/tree/fixAttempt/holdArmor) branch into master so you can try it now. I also tested my changes, and I was able to come back from the Commander Keen mission with the correct armor class.

**Comment by Username-N00b-is-not-available** [comment]
@Talon1024 Seems to work now, thanks! This leaves the princess message here. The problem only occurs in Russian for some reason, the translated message KEENLINDSEY1 is present in the CSV, and messages 2 and 3 by Keen show fine.
By the way, wouldn't the naive approach of copying ```BasicArmor``` and ```HexenArmor```, then altogether removing them, work? CK levels AFAIK do not need any armor at all. Is this just because the InventoryHolder might be later used in different situations?

**Comment by Talon1024** [comment]
> By the way, wouldn't the naive approach of copying `BasicArmor` and `HexenArmor`, then altogether removing them, work? CK levels AFAIK do not need any armor at all. Is this just because the InventoryHolder might be later used in different situations?

I'm not sure what exactly you mean. The approach that was used was to remove the item from the player's inventory and put it back in after the InventoryHolder's parent item was taken from the player. It didn't work because the player always has both a BasicArmor and a HexenArmor, and those items have the `+KEEPDEPLETED` flag. You can even see this when you start a new game in Doom 2 and enter `printinv` in the console. In BoA you can also enter `netevent showarmor` to print out information about your armor.

The InventoryHolder is used on the Allied HQ training course and the secret James Ryan mission in addition to the Commander Keen levels.

**Comment by Talon1024** [comment]
> @Talon1024 Seems to work now, thanks! This leaves the princess message here. The problem only occurs in Russian for some reason, the translated message KEENLINDSEY1 is present in the CSV, and messages 2 and 3 by Keen show fine.

That may be because the message is too long. Removing the first letter from the Russian version of KEENLINDSEY1 fixes it. However, I don't know what the underlying cause of that message box bug is.

**Comment by Username-N00b-is-not-available** [comment]
Shortening the message has indeed fixed it, thanks!
