### ISSUE TITLE
[3.2] C2M5_B UFO escape has no explosion

### ISSUE THREAD

**Issue by MuadDib90** [Realm667/WolfenDoom#986]
The UFO upon touching the hangar door just disappears, there is no longer (don't know how long already) any explosion (as I remember there was one actualy). There is present some lighting thought to give an impression of explosion.
![01](https://user-images.githubusercontent.com/73436978/126452630-72524e08-ae73-4e2e-80c9-70e123878b06.PNG)

**Comment by Tormentor667** [comment]
Culling issue @AFADoomer @Ozymandias81 @Talon1024 ?

**Comment by Ozymandias81** [comment]
Probably, it is something I will check later

**Comment by Username-N00b-is-not-available** [comment]
Yes, the explosion is too small, and we also need larger metal debris objects to fall from there instead of shrapnel we currently have.
Related to #872 (duplicate).

**Comment by Tormentor667** [comment]
Fully agreed with @Username-N00b-is-not-available

**Comment by MuadDib90** [comment]
Problem still persists...

**Comment by Tormentor667** [comment]
@AFADoomer can you fix this issue somehow by excluding the explosion from culling?

**Comment by Username-N00b-is-not-available** [comment]
When you rebase ```Nuke``` on ```Actor``` instead of ```SmokeBase```, the explosion regains its C2 look. I'll do this to all UFO-related explosion actors instead of just ```Nuke```.

**Comment by Username-N00b-is-not-available** [comment]
We still need large metal/electronics debris actors instead of lines https://github.com/Realm667/WolfenDoom/blob/36c0a2ae8e2f82ea5a0918ccde717344076cbd6b/scripts/decorate/models/scenery.zs#L2039-L2044 I think we could use actors including these:
```Debris_Mecha3, Debris_Mecha4, Debris_AstroSuite, Debris_AstroRobot, (something like) Surgery_Crab, JunkPileAstro.```
We still have some Doom image format sprites, by the way, and some unused sprites (see all frames of FMTL except A).
I believe at some point we had a large sprite of some electronics chunk with wire, is there any actor that uses it, or this is a false memory?

**Comment by Username-N00b-is-not-available** [comment]
I consider the explosion fine as of https://github.com/Realm667/WolfenDoom/commit/88a9c15626777879e5e05e82016767087cffe3d6, maybe I'll return to it later and try to make it less performance-intensive. Though being a one-time occurence, it is low priority.
